"use client"

import { createContext, useContext, useState, useCallback, type ReactNode } from "react"

export type Language = "es" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Header
    "nav.solutions": "Soluciones",
    "nav.modules": "Módulos",
    "nav.roi": "ROI",
    "nav.contact": "Contacto",
    "nav.requestDemo": "Solicitar Demo",

    // Hero
    "hero.badge": "Business Intelligence para Retail",
    "hero.title1": "La cultura es lo que sucede ",
    "hero.title2": "cuando el jefe no está",
    "hero.description": "Generamos hábitos de alto rendimiento en tu equipo a través de monitoreo inteligente, automatización de procesos y evidencia digital para la mejora continua.",
    "hero.cta.demo": "Solicitar Demo",
    "hero.cta.video": "Ver Video",
    "hero.trust.title": "Tecnología que impulsa la transformación",
    "hero.trust.iso": "ISO 27001",
    "hero.trust.iot": "IoT Certificado",
    "hero.trust.ai": "AI Vision",
    "hero.trust.branches": "+120 Sucursales",
    "hero.trust.users": "+3,000 Colaboradores",
    "hero.dashboard.title": "SIDÓN Dashboard",
    "hero.dashboard.energy": "Energía",
    "hero.dashboard.productivity": "Productividad",
    "hero.dashboard.incidents": "Incidentes",
    "hero.dashboard.audit": "Auditoría completada - Sucursal Norte",
    "hero.dashboard.sensor": "Sensor IoT calibrado - Refrigeración",
    "hero.dashboard.timeAgo1": "Hace 5 min",
    "hero.dashboard.timeAgo2": "Hace 12 min",

    // Stats
    "stats.title1": "Resultados que ",
    "stats.title2": "Transforman",
    "stats.subtitle": "Métricas reales de clientes que han implementado SIDÓN en sus operaciones",
    "stats.energy.label": "Ahorro Energético",
    "stats.energy.description": "Reducción en consumo eléctrico mediante monitoreo IoT inteligente",
    "stats.productivity.label": "Incremento en Productividad",
    "stats.productivity.description": "Mejora en eficiencia operativa con auditorías automatizadas",
    "stats.operation.label": "Días de Operación Confiable",
    "stats.operation.description": "Disponibilidad garantizada con soporte técnico 24/7",

    // Solutions
    "solutions.badge": "Módulos",
    "solutions.title1": "Soluciones Integrales para tu ",
    "solutions.title2": "Operación",
    "solutions.subtitle": "Cada módulo se integra perfectamente para crear un ecosistema completo de inteligencia operativa",
    "solutions.learnMore": "Conocer más",
    "solutions.sense.subtitle": "Monitoreo Inteligente",
    "solutions.sense.title": "Sense IoT",
    "solutions.sense.description": "Control y monitoreo de dispositivos en tiempo real. Sensores de temperatura, energía, humedad y más para optimizar tus operaciones.",
    "solutions.sense.feature1": "Alertas en tiempo real",
    "solutions.sense.feature2": "Dashboards personalizados",
    "solutions.sense.feature3": "Integración con equipos existentes",
    "solutions.audits.subtitle": "AI CCTV & Evidencia",
    "solutions.audits.title": "Smart Audits",
    "solutions.audits.description": "Auditorías automatizadas con inteligencia artificial. Genera evidencia digital para cumplimiento y mejora continua.",
    "solutions.audits.feature1": "Reconocimiento visual AI",
    "solutions.audits.feature2": "Reportes automáticos",
    "solutions.audits.feature3": "Evidencia fotográfica",
    "solutions.mantiz.subtitle": "Gestión de Mantenimiento",
    "solutions.mantiz.title": "Mantiz",
    "solutions.mantiz.description": "Sistema completo para la gestión preventiva y correctiva de mantenimientos. Reduce tiempos de paro y extiende la vida útil de equipos.",
    "solutions.mantiz.feature1": "Órdenes de trabajo digitales",
    "solutions.mantiz.feature2": "Calendario preventivo",
    "solutions.mantiz.feature3": "Historial de activos",
    "solutions.citas.subtitle": "Control de Acceso QR",
    "solutions.citas.title": "Citas",
    "solutions.citas.description": "Gestión de visitantes y proveedores con códigos QR. Registra entradas, salidas y genera reportes de asistencia.",
    "solutions.citas.feature1": "Check-in sin contacto",
    "solutions.citas.feature2": "Registro de visitantes",
    "solutions.citas.feature3": "Reportes de acceso",

    // Comparison
    "comparison.badge": "Transformación",
    "comparison.title1": "De Reactivo a ",
    "comparison.title2": "Predictivo",
    "comparison.subtitle": "Compara cómo SIDÓN transforma tu operación de un modelo tradicional a uno basado en datos e inteligencia artificial",
    "comparison.before.subtitle": "Modelo Reactivo",
    "comparison.before.title": "Situación Actual",
    "comparison.before.item1": "Auditorías manuales y esporádicas",
    "comparison.before.item2": "Sin evidencia digital de procesos",
    "comparison.before.item3": "Reacción tardía a fallas de equipos",
    "comparison.before.item4": "Control de acceso con bitácoras físicas",
    "comparison.before.item5": "Decisiones basadas en percepción",
    "comparison.before.item6": "Costos energéticos sin monitoreo",
    "comparison.after.subtitle": "Modelo Preventivo & Digital",
    "comparison.after.title": "Habilitación Sidón",
    "comparison.after.item1": "Auditorías automatizadas con AI",
    "comparison.after.item2": "Evidencia fotográfica y digital en tiempo real",
    "comparison.after.item3": "Mantenimiento preventivo inteligente",
    "comparison.after.item4": "Control de acceso digital con QR",
    "comparison.after.item5": "Decisiones basadas en datos",
    "comparison.after.item6": "Optimización energética con IoT",
    "comparison.recommended": "Recomendado",
    "comparison.cta": "Comenzar Transformación",
    "comparison.metrics.costs": "Costos Op.",
    "comparison.metrics.downtime": "Tiempo Paro",
    "comparison.metrics.efficiency": "Eficiencia",
    "comparison.trend.negative": "Tendencia negativa",
    "comparison.trend.positive": "ROI positivo confirmado",

    // Support
    "support.badge": "Soporte Estratégico",
    "support.title1": "Tu éxito es nuestra ",
    "support.title2": "prioridad",
    "support.description": "No solo te entregamos una plataforma, te acompañamos en cada paso de tu transformación digital con un equipo de expertos dedicados a maximizar el valor de tu inversión.",
    "support.csq.title": "Customer Success Quality",
    "support.csq.subtitle": "Metodología exclusiva SIDÓN",
    "support.csq.description": "Nuestro programa CSQ combina tecnología y acompañamiento humano para garantizar que cada cliente alcance sus objetivos de transformación operativa.",
    "support.feature1.title": "Customer Success Quality (CSQ)",
    "support.feature1.description": "Equipo dedicado a garantizar el éxito de tu implementación con métricas claras y seguimiento continuo.",
    "support.feature2.title": "Mesa de Ayuda 24/7",
    "support.feature2.description": "Soporte técnico disponible las 24 horas del día, los 365 días del año para resolver cualquier incidencia.",
    "support.feature3.title": "SLA Garantizado",
    "support.feature3.description": "Tiempos de respuesta comprometidos con niveles de servicio documentados y medibles.",
    "support.feature4.title": "Capacitación Continua",
    "support.feature4.description": "Programas de entrenamiento para tu equipo que aseguran la adopción completa de la plataforma.",
    "support.feature5.title": "Comunicación Proactiva",
    "support.feature5.description": "Te mantenemos informado con reportes periódicos y recomendaciones de mejora continua.",
    "support.feature6.title": "Seguridad Empresarial",
    "support.feature6.description": "Infraestructura robusta con certificaciones de seguridad y respaldos automáticos de información.",

    // CSQ Commitment
    "csq.badge": "Customer Success Quality",
    "csq.title1": "Nuestro Compromiso: ",
    "csq.title2": "Customer Success Quality",
    "csq.subtitle": "No somos solo soporte, somos tus consultores operativos",
    "csq.quote": "No somos solo soporte, somos tus consultores operativos",
    "csq.point1.title": "Configuración Personalizada",
    "csq.point1.description": "Adaptamos la plataforma a tus necesidades específicas, configurando cada módulo según los procesos únicos de tu operación.",
    "csq.point2.title": "Acompañamiento y Capacitación",
    "csq.point2.description": "Te guiamos con un lenguaje sencillo y accesible, asegurando que todo tu equipo domine la plataforma sin complicaciones.",
    "csq.point3.title": "Interpretación de Resultados",
    "csq.point3.description": "Analizamos tus datos y te brindamos insights accionables para maximizar el ROI de tu inversión tecnológica.",
    "csq.footer": "Comprometidos con tu éxito operativo desde el día uno",

    // ROI Section
    "roi.heading": "La cultura es lo que sucede cuando el jefe no está",
    "roi.subtitle": "SIDÓN no solo digitaliza, genera un impacto medible en los costos y la efectividad de tu equipo.",
    "roi.energy.title": "Ahorro Energético",
    "roi.energy.description": "Reducción directa en el consumo de A/C e iluminación mediante monitoreo inteligente.",
    "roi.productivity.title": "Mayor Productividad",
    "roi.productivity.description": "Optimización del tiempo de supervisión y ejecución efectiva de procesos diarios.",
    "roi.csq.badge": "Acompañamiento humano que garantiza tu éxito",
    "roi.activity.title": "Actividad en Tiempo Real",
    "roi.activity.1": "Auditoría completada por Supervisor en Sucursal Norte",
    "roi.activity.2": "Mantenimiento preventivo validado vía Mantiz",
    "roi.activity.3": "Reporte de temperatura aprobado - Planta Central",
    "roi.activity.4": "Checklist de seguridad completado - Almacén Sur",
    "roi.activity.5": "Inspección de equipos finalizada - Zona Industrial",
    "roi.activity.time.1": "Hace 5 min",
    "roi.activity.time.2": "Hace 12 min",
    "roi.activity.time.3": "Hace 18 min",
    "roi.activity.time.4": "Hace 25 min",
    "roi.activity.time.5": "Hace 32 min",
    "roi.cta.title": "Impacto Cualitativo Sostenible",
    "roi.cta.description": "Menor rotación de personal y decisiones más rápidas basadas en datos reales.",
    "roi.cta.button": "Calcular mi Retorno",

    // CSQ Commitment Section
    "csqSection.title": "Compromiso Humano: CSQ",
    "csqSection.subtitle": "Más que Software, un Socio en tu Operación",
    "csqSection.card1.title": "Consultoría Estratégica",
    "csqSection.card1.description": "Personalizamos SIDÓN según las necesidades específicas de tu operación. No vendemos un producto genérico, co-creamos la solución contigo.",
    "csqSection.card2.title": "Acompañamiento Humano",
    "csqSection.card2.description": "Hablamos el lenguaje de tu equipo operativo. Nuestros consultores están en campo, no solo detrás de un escritorio, garantizando adopción real.",
    "csqSection.card3.title": "Evolución de Resultados",
    "csqSection.card3.description": "Interpretamos tus datos y los convertimos en acciones concretas. Medimos el ROI contigo y ajustamos la estrategia en tiempo real.",
    "csqSection.closing": "Nuestra presencia es crítica para mantener la confiabilidad de tu operación los 365 días del año.",
    "csqSection.closing.highlight": "confiabilidad de tu operación",

    // Mantiz Timeline
    "mantiz.badge": "Gestión de Mantenimiento",
    "mantiz.title": "Ciclo Completo de Atención",
    "mantiz.subtitle": "Automatizamos y controlamos todo el ciclo de atención de incidencias técnicas",
    "mantiz.node1.title": "Reporte de Incidencia",
    "mantiz.node1.description": "El empleado detecta y reporta una falla técnica desde su smartphone en tiempo real.",
    "mantiz.node1.imageAlt": "Empleado reportando falla desde smartphone",
    "mantiz.node2.title": "Asignación Inteligente",
    "mantiz.node2.description": "El sistema asigna automáticamente la tarea al técnico disponible según ubicación y especialidad.",
    "mantiz.node2.imageAlt": "Dashboard administrativo asignando tarea",
    "mantiz.node3.title": "Validación en Campo",
    "mantiz.node3.description": "El técnico escanea código QR para validar su ubicación y registrar inicio de trabajo.",
    "mantiz.node3.imageAlt": "Técnico escaneando código QR",
    "mantiz.node4.title": "Cierre con Evidencia",
    "mantiz.node4.description": "Se valida la reparación con evidencia fotográfica antes y después, cerrando el ticket.",
    "mantiz.node4.imageAlt": "Pantalla de cierre de ticket con evidencia",
    "mantiz.cta": "Conocer Mantiz",

    // CTA
    "cta.title": "Comienza tu transformación digital hoy",
    "cta.description": "Agenda una demostración personalizada y descubre cómo SIDÓN puede optimizar las operaciones de tu negocio con inteligencia artificial y datos en tiempo real.",
    "cta.demo": "Solicitar Demo Gratuita",
    "cta.call": "Llamar Ahora",

    // Footer
    "footer.tagline": "Business Intelligence para retail. Transformamos datos en decisiones inteligentes.",
    "footer.solutions": "Soluciones",
    "footer.company": "Empresa",
    "footer.support": "Soporte",
    "footer.aboutUs": "Nosotros",
    "footer.successCases": "Casos de Éxito",
    "footer.blog": "Blog",
    "footer.careers": "Carreras",
    "footer.helpCenter": "Centro de Ayuda",
    "footer.documentation": "Documentación",
    "footer.api": "API",
    "footer.systemStatus": "Estado del Sistema",
    "footer.ecosat.title": "Una empresa de",
    "footer.ecosat.tagline": "Soluciones tecnológicas para la industria retail desde 2008.",
    "footer.copyright": "© 2026 SIDÓN by ECOSAT. Todos los derechos reservados.",
    "footer.privacy": "Privacidad",
    "footer.terms": "Términos",
    "footer.cookies": "Cookies",
  },
  en: {
    // Header
    "nav.solutions": "Solutions",
    "nav.modules": "Modules",
    "nav.roi": "ROI",
    "nav.contact": "Contact",
    "nav.requestDemo": "Request Demo",

    // Hero
    "hero.badge": "Business Intelligence for Retail",
    "hero.title1": "Culture is what happens ",
    "hero.title2": "when the boss isn't around",
    "hero.description": "We build high-performance habits in your team through intelligent monitoring, process automation, and digital evidence for continuous improvement.",
    "hero.cta.demo": "Request Demo",
    "hero.cta.video": "Watch Video",
    "hero.trust.title": "Technology that drives transformation",
    "hero.trust.iso": "ISO 27001",
    "hero.trust.iot": "Certified IoT",
    "hero.trust.ai": "AI Vision",
    "hero.trust.branches": "+120 Branches",
    "hero.trust.users": "+3,000 Team Members",
    "hero.dashboard.title": "SIDÓN Dashboard",
    "hero.dashboard.energy": "Energy",
    "hero.dashboard.productivity": "Productivity",
    "hero.dashboard.incidents": "Incidents",
    "hero.dashboard.audit": "Audit completed - North Branch",
    "hero.dashboard.sensor": "IoT Sensor calibrated - Refrigeration",
    "hero.dashboard.timeAgo1": "5 min ago",
    "hero.dashboard.timeAgo2": "12 min ago",

    // Stats
    "stats.title1": "Results that ",
    "stats.title2": "Transform",
    "stats.subtitle": "Real metrics from clients who have implemented SIDÓN in their operations",
    "stats.energy.label": "Energy Savings",
    "stats.energy.description": "Reduction in electrical consumption through intelligent IoT monitoring",
    "stats.productivity.label": "Productivity Increase",
    "stats.productivity.description": "Improvement in operational efficiency with automated audits",
    "stats.operation.label": "Days of Reliable Operation",
    "stats.operation.description": "Guaranteed availability with 24/7 technical support",

    // Solutions
    "solutions.badge": "Modules",
    "solutions.title1": "Comprehensive Solutions for your ",
    "solutions.title2": "Operation",
    "solutions.subtitle": "Each module integrates perfectly to create a complete operational intelligence ecosystem",
    "solutions.learnMore": "Learn more",
    "solutions.sense.subtitle": "Intelligent Monitoring",
    "solutions.sense.title": "Sense IoT",
    "solutions.sense.description": "Real-time device control and monitoring. Temperature, energy, humidity sensors and more to optimize your operations.",
    "solutions.sense.feature1": "Real-time alerts",
    "solutions.sense.feature2": "Custom dashboards",
    "solutions.sense.feature3": "Integration with existing equipment",
    "solutions.audits.subtitle": "AI CCTV & Evidence",
    "solutions.audits.title": "Smart Audits",
    "solutions.audits.description": "Automated audits with artificial intelligence. Generate digital evidence for compliance and continuous improvement.",
    "solutions.audits.feature1": "AI visual recognition",
    "solutions.audits.feature2": "Automatic reports",
    "solutions.audits.feature3": "Photographic evidence",
    "solutions.mantiz.subtitle": "Maintenance Management",
    "solutions.mantiz.title": "Mantiz",
    "solutions.mantiz.description": "Complete system for preventive and corrective maintenance management. Reduce downtime and extend equipment lifespan.",
    "solutions.mantiz.feature1": "Digital work orders",
    "solutions.mantiz.feature2": "Preventive calendar",
    "solutions.mantiz.feature3": "Asset history",
    "solutions.citas.subtitle": "QR Access Control",
    "solutions.citas.title": "Citas",
    "solutions.citas.description": "Visitor and supplier management with QR codes. Record entries, exits, and generate attendance reports.",
    "solutions.citas.feature1": "Contactless check-in",
    "solutions.citas.feature2": "Visitor registration",
    "solutions.citas.feature3": "Access reports",

    // Comparison
    "comparison.badge": "Transformation",
    "comparison.title1": "From Reactive to ",
    "comparison.title2": "Predictive",
    "comparison.subtitle": "Compare how SIDÓN transforms your operation from a traditional model to one based on data and artificial intelligence",
    "comparison.before.subtitle": "Reactive Model",
    "comparison.before.title": "Current Situation",
    "comparison.before.item1": "Manual and sporadic audits",
    "comparison.before.item2": "No digital evidence of processes",
    "comparison.before.item3": "Late response to equipment failures",
    "comparison.before.item4": "Access control with physical logs",
    "comparison.before.item5": "Decisions based on perception",
    "comparison.before.item6": "Energy costs without monitoring",
    "comparison.after.subtitle": "Preventive & Digital Model",
    "comparison.after.title": "Sidón Enablement",
    "comparison.after.item1": "Automated audits with AI",
    "comparison.after.item2": "Real-time photographic and digital evidence",
    "comparison.after.item3": "Intelligent preventive maintenance",
    "comparison.after.item4": "Digital access control with QR",
    "comparison.after.item5": "Data-driven decisions",
    "comparison.after.item6": "Energy optimization with IoT",
    "comparison.recommended": "Recommended",
    "comparison.cta": "Start Transformation",
    "comparison.metrics.costs": "Op. Costs",
    "comparison.metrics.downtime": "Downtime",
    "comparison.metrics.efficiency": "Efficiency",
    "comparison.trend.negative": "Negative trend",
    "comparison.trend.positive": "Positive ROI confirmed",

    // Support
    "support.badge": "Strategic Support",
    "support.title1": "Your success is our ",
    "support.title2": "priority",
    "support.description": "We don't just deliver a platform, we accompany you every step of your digital transformation with a team of experts dedicated to maximizing the value of your investment.",
    "support.csq.title": "Customer Success Quality",
    "support.csq.subtitle": "Exclusive SIDÓN methodology",
    "support.csq.description": "Our CSQ program combines technology and human support to ensure each client achieves their operational transformation goals.",
    "support.feature1.title": "Customer Success Quality (CSQ)",
    "support.feature1.description": "Team dedicated to ensuring your implementation success with clear metrics and continuous follow-up.",
    "support.feature2.title": "24/7 Help Desk",
    "support.feature2.description": "Technical support available 24 hours a day, 365 days a year to resolve any incident.",
    "support.feature3.title": "Guaranteed SLA",
    "support.feature3.description": "Committed response times with documented and measurable service levels.",
    "support.feature4.title": "Continuous Training",
    "support.feature4.description": "Training programs for your team that ensure complete platform adoption.",
    "support.feature5.title": "Proactive Communication",
    "support.feature5.description": "We keep you informed with periodic reports and continuous improvement recommendations.",
    "support.feature6.title": "Enterprise Security",
    "support.feature6.description": "Robust infrastructure with security certifications and automatic information backups.",

    // CSQ Commitment
    "csq.badge": "Customer Success Quality",
    "csq.title1": "Our Commitment: ",
    "csq.title2": "Customer Success Quality",
    "csq.subtitle": "We're not just support, we're your operational consultants",
    "csq.quote": "We're not just support, we're your operational consultants",
    "csq.point1.title": "Personalized Configuration",
    "csq.point1.description": "We adapt the platform to your specific needs, configuring each module according to your operation's unique processes.",
    "csq.point2.title": "Guidance and Training",
    "csq.point2.description": "We guide you with simple and accessible language, ensuring your entire team masters the platform without complications.",
    "csq.point3.title": "Results Interpretation",
    "csq.point3.description": "We analyze your data and provide actionable insights to maximize the ROI of your technology investment.",
    "csq.footer": "Committed to your operational success from day one",

    // ROI Section
    "roi.heading": "Culture is what happens when the boss isn't around",
    "roi.subtitle": "SIDÓN doesn't just digitize, it generates measurable impact on your costs and team effectiveness.",
    "roi.energy.title": "Energy Savings",
    "roi.energy.description": "Direct reduction in A/C and lighting consumption through intelligent monitoring.",
    "roi.productivity.title": "Increased Productivity",
    "roi.productivity.description": "Optimization of supervision time and effective execution of daily processes.",
    "roi.csq.badge": "Human support that guarantees your success",
    "roi.activity.title": "Real-Time Activity",
    "roi.activity.1": "Audit completed by Supervisor at North Branch",
    "roi.activity.2": "Preventive maintenance validated via Mantiz",
    "roi.activity.3": "Temperature report approved - Central Plant",
    "roi.activity.4": "Safety checklist completed - South Warehouse",
    "roi.activity.5": "Equipment inspection completed - Industrial Zone",
    "roi.activity.time.1": "5 min ago",
    "roi.activity.time.2": "12 min ago",
    "roi.activity.time.3": "18 min ago",
    "roi.activity.time.4": "25 min ago",
    "roi.activity.time.5": "32 min ago",
    "roi.cta.title": "Sustainable Qualitative Impact",
    "roi.cta.description": "Lower staff turnover and faster decisions based on real data.",
    "roi.cta.button": "Calculate My Return",

    // CSQ Commitment Section
    "csqSection.title": "Human Commitment: CSQ",
    "csqSection.subtitle": "More than Software, a Partner in Your Operation",
    "csqSection.card1.title": "Strategic Consulting",
    "csqSection.card1.description": "We customize SIDÓN according to your operation's specific needs. We don't sell a generic product, we co-create the solution with you.",
    "csqSection.card2.title": "Human Support",
    "csqSection.card2.description": "We speak your operational team's language. Our consultants are in the field, not just behind a desk, ensuring real adoption.",
    "csqSection.card3.title": "Results Evolution",
    "csqSection.card3.description": "We interpret your data and convert it into concrete actions. We measure ROI with you and adjust the strategy in real-time.",
    "csqSection.closing": "Our presence is critical to maintain the reliability of your operation 365 days a year.",
    "csqSection.closing.highlight": "reliability of your operation",

    // Mantiz Timeline
    "mantiz.badge": "Maintenance Management",
    "mantiz.title": "Complete Service Cycle",
    "mantiz.subtitle": "We automate and control the entire technical incident response cycle",
    "mantiz.node1.title": "Incident Report",
    "mantiz.node1.description": "Employee detects and reports a technical failure from their smartphone in real-time.",
    "mantiz.node1.imageAlt": "Employee reporting failure from smartphone",
    "mantiz.node2.title": "Smart Assignment",
    "mantiz.node2.description": "The system automatically assigns the task to the available technician based on location and specialty.",
    "mantiz.node2.imageAlt": "Admin dashboard assigning task",
    "mantiz.node3.title": "Field Validation",
    "mantiz.node3.description": "Technician scans QR code to validate location and register work start.",
    "mantiz.node3.imageAlt": "Technician scanning QR code",
    "mantiz.node4.title": "Evidence-Based Closure",
    "mantiz.node4.description": "Repair is validated with before and after photographic evidence, closing the ticket.",
    "mantiz.node4.imageAlt": "Ticket closure screen with evidence",
    "mantiz.cta": "Learn About Mantiz",

    // CTA
    "cta.title": "Start your digital transformation today",
    "cta.description": "Schedule a personalized demo and discover how SIDÓN can optimize your business operations with artificial intelligence and real-time data.",
    "cta.demo": "Request Free Demo",
    "cta.call": "Call Now",

    // Footer
    "footer.tagline": "Business Intelligence for retail. We transform data into intelligent decisions.",
    "footer.solutions": "Solutions",
    "footer.company": "Company",
    "footer.support": "Support",
    "footer.aboutUs": "About Us",
    "footer.successCases": "Success Cases",
    "footer.blog": "Blog",
    "footer.careers": "Careers",
    "footer.helpCenter": "Help Center",
    "footer.documentation": "Documentation",
    "footer.api": "API",
    "footer.systemStatus": "System Status",
    "footer.ecosat.title": "A company of",
    "footer.ecosat.tagline": "Technology solutions for the retail industry since 2008.",
    "footer.copyright": "© 2026 SIDÓN by ECOSAT. All rights reserved.",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.cookies": "Cookies",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("es")

  const t = useCallback(
    (key: string): string => {
      return translations[language][key] || key
    },
    [language]
  )

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
