"use client"

import { createContext, useContext, useState, useCallback, type ReactNode } from "react"

export type Language = "es" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Header
    "nav.solutions": "Soluciones",
    "nav.modules": "Módulos",
    "nav.roi": "ROI",
    "nav.contact": "Contacto",
    "nav.requestDemo": "Solicitar Demo",
    "nav.modules.all": "Ver todos los módulos",
    "nav.modules.sense": "Sense IOT",
    "nav.modules.audits": "Smart Audits",
    "nav.modules.citas": "Smart Citas",
    "nav.modules.mantenimiento": "Sidon Mantiz",
    "nav.modules.duma": "DUMA Agente AI",

    // Hero
    "hero.badge": "Business Intelligence para CEOs",
    "hero.title1": "Toma control real de tu operación.",
    "hero.title2": "Incluso cuando no estás.",
    "hero.description": "Sidón acompaña a CEOs a reducir costos, elevar productividad y mejorar el desempeño operativo mediante experiencia real, procesos claros y AI aplicada.",
    "hero.cta.primary": "Ver cómo Sidón genera ahorro y control",
    "hero.cta.secondary": "Solicitar demo",
    "hero.impact.title": "Impacto Ejecutivo",
    "hero.impact.savings.title": "Ahorro operativo",
    "hero.impact.savings.description": "Gestión energética inteligente, menos mermas y reprocesos.",
    "hero.impact.productivity.title": "Productividad",
    "hero.impact.productivity.description": "Equipos alineados, menos supervisión directa.",
    "hero.impact.performance.title": "Desempeño operativo",
    "hero.impact.performance.description": "Auditoría continua, evidencia y mejora diaria.",
    "hero.impact.culture.title": "Cultura",
    "hero.impact.culture.description": "Disciplina operativa sostenida por el sistema Sidón.",
    "hero.trust.title": "Implementación acompañada · Solución llave en mano · Evidencia diaria",
    "hero.social.proof": "+350 sucursales · +3,000 personas · Operación real",

    // Duma Section
    "duma.badge": "Agente Operativo",
    "duma.title1": "DUMA: No es otro dashboard,",
    "duma.title2": "es tu cerebro operativo.",
    "duma.description": "Mientras un dashboard normal te muestra que algo falló ayer, DUMA actúa hoy. Traduce la \"data dura\" de Sidón en acciones concretas para tu staff, eliminando la brecha entre el reporte y la resolución.",
    "duma.hours": "Horas recuperadas al día",
    "duma.traceability": "Trazabilidad de acciones",
    "duma.fatigue.title": "La \"Fatiga de Datos\" hoy:",
    "duma.fatigue.search": "Buscar información",
    "duma.fatigue.consolidate": "Consolidar datos",
    "duma.fatigue.format": "Dar formato",
    "duma.fatigue.report": "Generar reportes",
    "duma.fatigue.quote": "\"Los coordinadores pierden el 50% de su jornada en reporteo manual\"",
    "duma.fatigue.solution": "DUMA elimina el Proceso Manual al 100%",
    "duma.loop.title": "Ejecución inmediata con Closed Loop",
    "duma.loop.description": "Del 'Insight' a la 'Acción' en un clic. Duma no reemplaza a Sidón; lo potencia convirtiendo la inteligencia en ejecución.",
    "duma.step.insight.title": "Insight",
    "duma.step.insight.desc": "Duma detecta el problema analizando múltiples fuentes (SAP, Excel, Sidón) en milisegundos.",
    "duma.step.insight.detail": "Detecta: Venta -15% en Sucursal Norte",
    "duma.step.action.title": "Acción",
    "duma.step.action.desc": "Convierte el dato en una tarea operativa directa sin que el CEO tenga que intervenir.",
    "duma.step.action.detail": "Tarea: 'Revisar inventario de perecederos'",
    "duma.step.resolution.title": "Resolución",
    "duma.step.resolution.desc": "El staff en tienda recibe la instrucción y resuelve en campo, cerrando la brecha operativa.",
    "duma.step.resolution.detail": "Estado: Ejecutado por Gerente de Tienda",
    "duma.step.memory.title": "Memoria",
    "duma.step.memory.desc": "Todo queda registrado. El sistema aprende de las causas raíz para evitar incidencias futuras.",
    "duma.step.memory.detail": "Registro: Evidencia fotográfica y ahorro guardado",
    "duma.footer.quote": "\"Duma traduce los números en tareas operativas diarias.\"",
    "duma.footer.priority": "Priorización automática",
    "duma.footer.agent": "Agente 24/7 sobre Sidón",
    "duma.footer.error": "Cero margen de error manual",

    "hero.dashboard.status1": "Operación en estándar",
    "hero.dashboard.status2": "Energía bajo control",
    "hero.dashboard.status3": "Riesgos prevenidos",
    "hero.dashboard.status4": "Auditoría completada hoy",

    // Stats
    "stats.title1": "Resultados que ",
    "stats.title2": "Transforman",
    "stats.subtitle": "Métricas reales de clientes que han implementado SIDÓN en sus operaciones",
    "stats.energy.label": "Ahorro Energético",
    "stats.energy.description": "Reducción en consumo eléctrico mediante monitoreo IoT inteligente",
    "stats.productivity.label": "Incremento en Productividad",
    "stats.productivity.description": "Mejora en eficiencia operativa con auditorías automatizadas",
    "stats.operation.label": "Días de Operación Confiable",
    "stats.operation.description": "Disponibilidad garantizada con soporte técnico 24/7",

    // Solutions
    "solutions.badge": "Módulos",
    "solutions.title1": "Soluciones Integrales para tu ",
    "solutions.title2": "Operación",
    "solutions.subtitle": "Cada módulo se integra perfectamente para crear un ecosistema completo de inteligencia operativa",
    "solutions.learnMore": "Conocer más",
    "solutions.sense.subtitle": "Monitoreo Inteligente",
    "solutions.sense.title": "Sense IoT",
    "solutions.sense.description": "Control y monitoreo de dispositivos en tiempo real. Sensores de temperatura, energía, humedad y más para optimizar tus operaciones.",
    "solutions.sense.feature1": "Alertas en tiempo real",
    "solutions.sense.feature2": "Dashboards personalizados",
    "solutions.sense.feature3": "Integración con equipos existentes",
    "solutions.audits.subtitle": "AI CCTV & Evidencia",
    "solutions.audits.title": "Smart Audits",
    "solutions.audits.description": "Auditorías automatizadas con inteligencia artificial. Genera evidencia digital para cumplimiento y mejora continua.",
    "solutions.audits.feature1": "Reconocimiento visual AI",
    "solutions.audits.feature2": "Reportes automáticos",
    "solutions.audits.feature3": "Evidencia fotográfica",
    "solutions.mantiz.subtitle": "Gestión de Mantenimiento",
    "solutions.mantiz.title": "Mantiz",
    "solutions.mantiz.description": "Sistema completo para la gestión preventiva y correctiva de mantenimientos. Reduce tiempos de paro y extiende la vida útil de equipos.",
    "solutions.mantiz.feature1": "Órdenes de trabajo digitales",
    "solutions.mantiz.feature2": "Calendario preventivo",
    "solutions.mantiz.feature3": "Historial de activos",
    "solutions.citas.subtitle": "Control de Acceso QR",
    "solutions.citas.title": "Citas",
    "solutions.citas.description": "Gestión de visitantes y proveedores con códigos QR. Registra entradas, salidas y genera reportes de asistencia.",
    "solutions.citas.feature1": "Check-in sin contacto",
    "solutions.citas.feature2": "Registro de visitantes",
    "solutions.citas.feature3": "Reportes de acceso",

    // Comparison
    "comparison.badge": "Transformación",
    "comparison.title1": "De Reactivo a ",
    "comparison.title2": "Predictivo",
    "comparison.subtitle": "Compara cómo SIDÓN transforma tu operación de un modelo tradicional a uno basado en datos e inteligencia artificial",
    "comparison.before.subtitle": "Modelo Reactivo",
    "comparison.before.title": "Situación Actual",
    "comparison.before.item1": "Auditorías manuales y esporádicas",
    "comparison.before.item2": "Sin evidencia digital de procesos",
    "comparison.before.item3": "Reacción tardía a fallas de equipos",
    "comparison.before.item4": "Control de acceso con bitácoras físicas",
    "comparison.before.item5": "Decisiones basadas en percepción",
    "comparison.before.item6": "Costos energéticos sin monitoreo",
    "comparison.after.subtitle": "Modelo Preventivo & Digital",
    "comparison.after.title": "Habilitación Sidón",
    "comparison.after.item1": "Auditorías automatizadas con AI",
    "comparison.after.item2": "Evidencia fotográfica y digital en tiempo real",
    "comparison.after.item3": "Mantenimiento preventivo inteligente",
    "comparison.after.item4": "Control de acceso digital con QR",
    "comparison.after.item5": "Decisiones basadas en datos",
    "comparison.after.item6": "Optimización energética con IoT",
    "comparison.recommended": "Recomendado",
    "comparison.cta": "Comenzar Transformación",
    "comparison.metrics.costs": "Costos Op.",
    "comparison.metrics.downtime": "Tiempo Paro",
    "comparison.metrics.efficiency": "Eficiencia",
    "comparison.trend.negative": "Tendencia negativa",
    "comparison.trend.positive": "ROI positivo confirmado",

    // Support
    "support.badge": "Soporte Estratégico",
    "support.title1": "Tu éxito es nuestra ",
    "support.title2": "prioridad",
    "support.description": "No solo te entregamos una plataforma, te acompañamos en cada paso de tu transformación digital con un equipo de expertos dedicados a maximizar el valor de tu inversión.",
    "support.csq.title": "Customer Success Manager",
    "support.csq.subtitle": "Metodología exclusiva SIDÓN",
    "support.csq.description": "Nuestro programa CSM combina tecnología y acompañamiento humano para garantizar que cada cliente alcance sus objetivos de transformación operativa.",
    "support.feature1.title": "Customer Success Manager (CSM)",
    "support.feature1.description": "Equipo dedicado a garantizar el éxito de tu implementación con métricas claras y seguimiento continuo.",
    "support.feature2.title": "Mesa de Ayuda",
    "support.feature2.description": "Soporte técnico disponible según las necesidades de tu servicio para resolver cualquier incidencia.",
    "support.feature3.title": "SLA Garantizado",
    "support.feature3.description": "Tiempos de respuesta comprometidos con niveles de servicio documentados y medibles.",
    "support.feature4.title": "Capacitación Continua",
    "support.feature4.description": "Programas de entrenamiento para tu equipo que aseguran la adopción completa de la plataforma.",
    "support.feature5.title": "Comunicación Proactiva",
    "support.feature5.description": "Te mantenemos informado con reportes periódicos y recomendaciones de mejora continua.",
    "support.feature6.title": "Seguridad Empresarial",
    "support.feature6.description": "Infraestructura robusta con certificaciones de seguridad y respaldos automáticos de información.",

    // CSM Commitment
    "csq.badge": "Customer Success Manager",
    "csq.title1": "Nuestro Compromiso: ",
    "csq.title2": "Customer Success Manager",
    "csq.subtitle": "No somos solo soporte, somos tus consultores operativos",
    "csq.quote": "No somos solo soporte, somos tus consultores operativos",
    "csq.point1.title": "Configuración Personalizada",
    "csq.point1.description": "Adaptamos la plataforma a tus necesidades específicas, configurando cada módulo según los procesos únicos de tu operación.",
    "csq.point2.title": "Acompañamiento y Capacitación",
    "csq.point2.description": "Te guiamos con un lenguaje sencillo y accesible, asegurando que todo tu equipo domine la plataforma sin complicaciones.",
    "csq.point3.title": "Interpretación de Resultados",
    "csq.point3.description": "Analizamos tus datos y te brindamos insights accionables para maximizar el ROI de tu inversión tecnológica.",
    "csq.footer": "Comprometidos con tu éxito operativo desde el día uno",

    // ROI Section
    "roi.heading": "La cultura es lo que sucede cuando el jefe no está",
    "roi.subtitle": "SIDÓN no solo digitaliza, genera un impacto medible en los costos y la efectividad de tu equipo.",
    "roi.energy.title": "Ahorro Energético",
    "roi.energy.description": "Reducción directa en el consumo de A/C e iluminación mediante monitoreo inteligente.",
    "roi.productivity.title": "Mayor Productividad",
    "roi.productivity.description": "Optimización del tiempo de supervisión y ejecución efectiva de procesos diarios.",
    "roi.csm.badge": "Acompañamiento humano que garantiza tu éxito",
    "roi.activity.title": "Actividad en Tiempo Real",
    "roi.activity.1": "Auditoría completada por Supervisor en Sucursal Norte",
    "roi.activity.2": "Mantenimiento preventivo validado vía Mantiz",
    "roi.activity.3": "Reporte de temperatura aprobado - Planta Central",
    "roi.activity.4": "Checklist de seguridad completado - Almacén Sur",
    "roi.activity.5": "Inspección de equipos finalizada - Zona Industrial",
    "roi.activity.time.1": "Hace 5 min",
    "roi.activity.time.2": "Hace 12 min",
    "roi.activity.time.3": "Hace 18 min",
    "roi.activity.time.4": "Hace 25 min",
    "roi.activity.time.5": "Hace 32 min",
    "roi.cta.title": "Impacto Cualitativo Sostenible",
    "roi.cta.description": "Menor rotación de personal y decisiones más rápidas basadas en datos reales.",
    "roi.cta.button": "Calcular mi Retorno",

    // CSM Commitment Section
    "csqSection.title": "Compromiso Humano: CSM",
    "csqSection.subtitle": "Más que Software, un Socio en tu Operación",
    "csqSection.card1.title": "Consultoría Estratégica",
    "csqSection.card1.description": "Personalizamos SIDÓN según las necesidades específicas de tu operación. No vendemos un producto genérico, co-creamos la solución contigo.",
    "csqSection.card2.title": "Acompañamiento Humano",
    "csqSection.card2.description": "Hablamos el lenguaje de tu equipo operativo. Nuestros consultores están en campo, no solo detrás de un escritorio, garantizando adopción real.",
    "csqSection.card3.title": "Evolución de Resultados",
    "csqSection.card3.description": "Interpretamos tus datos y los convertimos en acciones concretas. Medimos el ROI contigo y ajustamos la estrategia en tiempo real.",
    "csqSection.closing": "Nuestra presencia es crítica para mantener la confiabilidad de tu operación los 365 días del año.",
    "csqSection.closing.highlight": "confiabilidad de tu operación",

    // Mantiz Timeline
    "mantiz.badge": "Gestión de Mantenimiento",
    "mantiz.title": "Ciclo Completo de Atención",
    "mantiz.subtitle": "Automatizamos y controlamos todo el ciclo de atención de incidencias técnicas",
    "mantiz.node1.title": "Reporte de Incidencia",
    "mantiz.node1.description": "El empleado detecta y reporta una falla técnica desde su smartphone en tiempo real.",
    "mantiz.node1.imageAlt": "Empleado reportando falla desde smartphone",
    "mantiz.node2.title": "Asignación Inteligente",
    "mantiz.node2.description": "El sistema asigna automáticamente la tarea al técnico disponible según ubicación y especialidad.",
    "mantiz.node2.imageAlt": "Dashboard administrativo asignando tarea",
    "mantiz.node3.title": "Validación en Campo",
    "mantiz.node3.description": "El técnico escanea código QR para validar su ubicación y registrar inicio de trabajo.",
    "mantiz.node3.imageAlt": "Técnico escaneando código QR",
    "mantiz.node4.title": "Cierre con Evidencia",
    "mantiz.node4.description": "Se valida la reparación con evidencia fotográfica antes y después, cerrando el ticket.",
    "mantiz.node4.imageAlt": "Pantalla de cierre de ticket con evidencia",
    "mantiz.cta": "Conocer Mantiz",

    // CTA
    "cta.title": "Comienza tu transformación digital hoy",
    "cta.description": "Agenda una demostración personalizada y descubre cómo SIDÓN puede optimizar las operaciones de tu negocio con inteligencia artificial y datos en tiempo real.",
    "cta.demo": "Solicitar Demo",
    "cta.call": "Llamar Ahora",

    // Footer
    "footer.tagline": "Business Intelligence para retail. Transformamos datos en decisiones inteligentes.",
    "footer.solutions": "Soluciones",
    "footer.company": "Empresa",
    "footer.support": "Soporte",
    "footer.aboutUs": "Nosotros",
    "footer.successCases": "Casos de Éxito",
    "footer.blog": "Blog",
    "footer.careers": "Carreras",
    "footer.helpCenter": "Centro de Ayuda",
    "footer.documentation": "Documentación",
    "footer.api": "API",
    "footer.systemStatus": "Estado del Sistema",
    "footer.ecosat.title": "Un producto de",
    "footer.ecosat.tagline": "Soluciones tecnológicas para la industria retail desde 2008.",
    "footer.copyright": "© 2026 SIDÓN by ECOSAT. Todos los derechos reservados.",
    "footer.privacy": "Privacidad",
    "footer.terms": "Términos",
    "footer.cookies": "Cookies",

    // Sense IoT Page
    "sense.hero.badge": "Internet de las Cosas (IoT)",
    "sense.hero.title1": "Inteligencia que siente,",
    "sense.hero.title2": "Datos que actúan.",
    "sense.hero.description": "Sidón Sense conecta tu infraestructura física con tu estrategia digital. Sensores industriales de alta precisión que transforman cada rincón de tu operación en una fuente de ahorro y control.",
    "sense.hero.cta": "Comenzar monitoreo",

    "sense.bento.cold.title": "Control de Frío Crítico",
    "sense.bento.cold.desc": "Monitoreo 24/7 de cámaras y refrigeradores. Evita mermas por cadena de frío rota.",
    "sense.bento.energy.title": "Gestión de Energía",
    "sense.bento.energy.desc": "Visualiza el consumo en tiempo real. Detecta equipos ineficientes y fugas eléctricas.",
    "sense.bento.ambient.title": "Variables Ambientales",
    "sense.bento.ambient.desc": "Humedad, CO2 y VOCs. Garantiza ambientes óptimos para clientes y productos.",
    "sense.bento.assets.title": "Salud de Activos",
    "sense.bento.assets.desc": "Vibración y corriente en motores. Predice fallas antes de que detengan tu operación.",

    "sense.workflow.title": "Del Sensor a la Decisión",
    "sense.workflow.step1.title": "Captura Precisa",
    "sense.workflow.step1.desc": "Sensores industriales Plug & Play miden variables críticas cada segundo.",
    "sense.workflow.step2.title": "Transmisión Segura",
    "sense.workflow.step2.desc": "Gateways con encriptación militar envían la data vía 4G o LoRaWAN.",
    "sense.workflow.step3.title": "Nube Sidón",
    "sense.workflow.step3.desc": "Algoritmos de AI analizan tendencias y detectan anomalías instantáneamente.",
    "sense.workflow.step4.title": "Closed Loop",
    "sense.workflow.step4.desc": "Si algo falla, DUMA asigna la tarea al técnico y cierra el ciclo.",

    "sense.benefits.title": "Impacto Directo en tu Bottom-Line",
    "sense.benefits.1.title": "Reducción de Mermas",
    "sense.benefits.1.desc": "Hasta un 30% menos de pérdida de producto por fallas en refrigeración.",
    "sense.benefits.2.title": "Ahorro Energético",
    "sense.benefits.2.desc": "Optimización de horarios y detección de consumos fantasma (-15% factura).",
    "sense.benefits.3.title": "Cumplimiento Normativo",
    "sense.benefits.3.desc": "Reportes automáticos para entidades regulatorias.",

    // SmartAudits Page
    "audits.hero.badge": "Gestión de Auditorías",
    "audits.hero.title1": "Control real de la ejecución operativa",
    "audits.hero.title2": "mediante auditorías inteligentes",
    "audits.hero.description": "SmartAudits automatiza la gestión, ejecución y supervisión de auditorías mediante IA, reduciendo errores y elevando el cumplimiento.",
    "audits.hero.cta": "Solicitar demo",
    "audits.hero.cta2": "Ver cómo funciona",
    "audits.problem.title": "El fin de la auditoría reactiva",
    "audits.problem.desc": "Supera los dolores reales de la supervisión tradicional.",
    "audits.problem.1.title": "Auditorías manuales",
    "audits.problem.1.desc": "Procesos predecibles que no reflejan la realidad diaria.",
    "audits.problem.2.title": "Falta de evidencia",
    "audits.problem.2.desc": "Reportes sin sustento objetivo ni validación visual.",
    "audits.problem.3.title": "Supervisión lenta",
    "audits.problem.3.desc": "Reacción tardía cuando el problema ya afectó la operación.",
    "audits.problem.4.title": "Cumplimiento inconsistente",
    "audits.problem.4.desc": "Variabilidad en la ejecución entre diferentes turnos o sucursales.",
    "audits.whatis.title": "¿Qué es SmartAudits?",
    "audits.whatis.subtitle": "Disciplina Operativa y Control Continuo",
    "audits.whatis.description": "Una plataforma de auditoría operativa inteligente con gestión de tareas asistida por IA para garantizar la excelencia en cada punto de contacto.",
    "audits.features.title": "Capacidades de Próxima Generación",
    "audits.features.1.title": "Asignación Automática",
    "audits.features.1.desc": "La IA programa tareas dinámicamente según prioridades operativas.",
    "audits.features.2.title": "Ejecución Aleatoria",
    "audits.features.2.desc": "Elimina la previsibilidad y garantiza una supervisión real y honesta.",
    "audits.features.3.title": "Evidencia Visual",
    "audits.features.3.desc": "Captura de imágenes por cada tarea con validación inmediata.",
    "audits.features.4.title": "Análisis con IA",
    "audits.features.4.desc": "La IA valida automáticamente el cumplimiento analizando las imágenes.",
    "audits.workflow.title": "Flujo de Ejecución Inteligente",
    "audits.workflow.step1.title": "Asignación IA",
    "audits.workflow.step1.desc": "La IA asigna y programa auditorías de forma inteligente y estratégica.",
    "audits.workflow.step2.title": "Ejecución en Campo",
    "audits.workflow.step2.desc": "El personal ejecuta las tareas asignadas guiado por la plataforma.",
    "audits.workflow.step3.title": "Evidencia visual",
    "audits.workflow.step3.desc": "Se captura evidencia visual objetiva de cada tarea realizada.",
    "audits.workflow.step4.title": "Validación y Decisión",
    "audits.workflow.step4.desc": "La IA analiza el cumplimiento y los supervisores toman decisiones.",
    "audits.benefits.title": "Resultados de Alto Impacto",
    "audits.benefits.1.title": "Menos Errores",
    "audits.benefits.1.desc": "Reducción drástica de fallas mediante procesos estandarizados.",
    "audits.benefits.2.title": "Objetividad Total",
    "audits.benefits.2.desc": "Auditorías basadas en datos y evidencia visual objetiva.",
    "audits.benefits.3.title": "Ahorro de Tiempo",
    "audits.benefits.3.desc": "Optimización radical del tiempo de supervisión y reporte.",
    "audits.footer.tagline": "Con SmartAudits, la innovación se convierte en eficiencia.",
    "audits.footer.cta1": "Automatiza. Simplifica. Avanza.",
    "audits.footer.demo": "Solicitar demo",
    "audits.footer.expert": "Contactar a un asesor",

    // Smart Citas Page
    "citas.hero.badge": "Gestión de Accesos",
    "citas.hero.title1": "Plataforma integral de",
    "citas.hero.title2": "Citas y Control de Visitantes",
    "citas.hero.description": "Optimiza tu recepción para reducir costos operativos y elevar la productividad. Citas Smart automatiza accesos, notificaciones y validaciones, eliminando cuellos de botella desde una sola plataforma.",
    "citas.hero.cta": "Solicitar demo",
    "citas.hero.cta2": "Conocer la solución",

    "citas.problem.title": "El caos en la recepción cuesta de más.",
    "citas.problem.item1.title": "Registro Manual",
    "citas.problem.item1.desc": "Procesos en papel, desordenados y sin validación real.",
    "citas.problem.item2.title": "Falta de Trazabilidad",
    "citas.problem.item2.desc": "Imposibilidad de auditar quién entró, a qué hora y por qué motivo.",
    "citas.problem.item3.title": "Recepción Lenta",
    "citas.problem.item3.desc": "Cuellos de botella que afectan la imagen corporativa y la productividad.",
    "citas.problem.item4.title": "Riesgos de Seguridad",
    "citas.problem.item4.desc": "Vulnerabilidad ante ingresos no autorizados y falta de control de políticas.",

    "citas.about.title": "¿Qué es Citas Smart?",
    "citas.about.desc1": "Es el módulo especializado de Sidón diseñado para optimizar y automatizar el ciclo completo de registro y control de visitantes.",
    "citas.about.desc2": "Desde la agenda hasta el ingreso validado, Citas Smart garantiza que cada persona que entra a tus instalaciones esté autorizada, registrada y monitoreada.",

    "citas.features.title": "Funcionalidades Clave",
    "citas.features.1.title": "Gestión de Agenda",
    "citas.features.1.desc": "Alta de citas por visitante, motivo y área específica de visita.",
    "citas.features.2.title": "Notificación QR",
    "citas.features.2.desc": "Envío automático de código QR personalizado vía correo electrónico y WhatsApp.",
    "citas.features.3.title": "Integración Total",
    "citas.features.3.desc": "Sincronización nativa con Google Calendar para una agenda unificada.",
    "citas.features.4.title": "Validación de Arribo",
    "citas.features.4.desc": "Check-in rápido mediante QR con validación de fecha, hora y área. Notificación inmediata al anfitrión.",

    "citas.security.title": "Control y Seguridad de Nivel Ejecutivo",
    "citas.security.desc": "No solo registramos visitas, protegemos tu operación mediante estándares de cumplimiento y privacidad.",
    "citas.security.item1": "Registro digital con captura de imagen y documento oficial.",
    "citas.security.item2": "Histórico detallado de visitas por persona y frecuencia.",
    "citas.security.item3": "Control de accesos dinámico conforme a políticas internas.",

    "citas.benefits.title": "Impacto Directo: Menores Costos, Mayor Productividad",
    "citas.benefits.1.title": "Acceso Ordenado y Rentable",
    "citas.benefits.1.desc": "Elimina las filas y el desorden en los puntos de ingreso.",
    "citas.benefits.2.title": "Comunicación Real",
    "citas.benefits.2.desc": "Anfitriones notificados al instante, listos para recibir a su visita.",
    "citas.benefits.3.title": "Trazabilidad Total",
    "citas.benefits.3.desc": "Control absoluto del flujo de personas en tiempo real.",

    "citas.footer.tagline": "ORDEN, SEGURIDAD Y CONTROL",
    "citas.footer.cta1": "Control desde el primer contacto.",
    "citas.footer.demo": "Solicitar demo",
    "citas.footer.expert": "Contactar a un asesor",

    // Contact Form
    "contact.title": "Contacta con Ventas",
    "contact.subtitle": "¿Listo para transformar tu operación? Nuestro equipo de ventas está aquí para ayudarte.",
    "contact.name": "Nombre completo",
    "contact.email": "Correo electrónico",
    "contact.company": "Empresa",
    "contact.message": "Mensaje",
    "contact.submit": "Enviar mensaje",
    "contact.sending": "Enviando...",
    "contact.success": "Mensaje enviado exitosamente. Nos pondremos en contacto contigo pronto.",
  },
  en: {
    // Header
    "nav.solutions": "Solutions",
    "nav.modules": "Modules",
    "nav.roi": "ROI",
    "nav.contact": "Contact",
    "nav.requestDemo": "Request Demo",
    "nav.modules.all": "See all modules",
    "nav.modules.sense": "Sense IOT",
    "nav.modules.audits": "Smart Audits",
    "nav.modules.citas": "Smart Citas",
    "nav.modules.mantenimiento": "Sidon Mantiz",
    "nav.modules.duma": "DUMA AI Agent",

    // Hero
    "hero.badge": "Business Intelligence for CEOs",
    "hero.title1": "Take real control of your operation.",
    "hero.title2": "Even when you're not there.",
    "hero.description": "Sidón helps CEOs reduce costs, increase productivity, and improve operational performance through real experience, clear processes, and applied AI.",
    "hero.cta.primary": "See how Sidón generates savings and control",
    "hero.cta.secondary": "Request demo",
    "hero.impact.title": "Executive Impact",
    "hero.impact.savings.title": "Operational savings",
    "hero.impact.savings.description": "Intelligent energy management, less waste and rework.",
    "hero.impact.productivity.title": "Productivity",
    "hero.impact.productivity.description": "Aligned teams, less direct supervision.",
    "hero.impact.performance.title": "Operational performance",
    "hero.impact.performance.description": "Continuous audit, evidence and daily improvement.",
    "hero.impact.culture.title": "Culture",
    "hero.impact.culture.description": "Operational discipline sustained by the Sidón system.",
    "hero.trust.title": "Guided implementation · Turnkey solution · Daily evidence",
    "hero.social.proof": "+350 branches · +3,000 people · Real operation",

    // Duma Section
    "duma.badge": "Operational Agent",
    "duma.title1": "DUMA: Not another dashboard,",
    "duma.title2": "is your operational brain.",
    "duma.description": "While a normal dashboard shows you what failed yesterday, DUMA acts today. It translates Sidón's \"hard data\" into concrete actions for your staff, eliminating the gap between reporting and resolution.",
    "duma.hours": "Hours recovered daily",
    "duma.traceability": "Traceability of actions",
    "duma.fatigue.title": "Today's \"Data Fatigue\":",
    "duma.fatigue.search": "Search information",
    "duma.fatigue.consolidate": "Consolidate data",
    "duma.fatigue.format": "Format data",
    "duma.fatigue.report": "Generate reports",
    "duma.fatigue.quote": "\"Coordinators lose 50% of their workday in manual reporting\"",
    "duma.fatigue.solution": "DUMA eliminates Manual Process by 100%",
    "duma.loop.title": "Immediate execution with Closed Loop",
    "duma.loop.description": "From 'Insight' to 'Action' in one click. Duma doesn't replace Sidón; it enhances it by turning intelligence into execution.",
    "duma.step.insight.title": "Insight",
    "duma.step.insight.desc": "Duma detects the problem by analyzing multiple sources (SAP, Excel, Sidón) in milliseconds.",
    "duma.step.insight.detail": "Detects: Sales -15% in North Branch",
    "duma.step.action.title": "Action",
    "duma.step.action.desc": "Converts data into a direct operational task without CEO intervention.",
    "duma.step.action.detail": "Task: 'Check perishable inventory'",
    "duma.step.resolution.title": "Resolution",
    "duma.step.resolution.desc": "Store staff receives instruction and resolves in the field, closing the operational gap.",
    "duma.step.resolution.detail": "Status: Executed by Store Manager",
    "duma.step.memory.title": "Memory",
    "duma.step.memory.desc": "Everything is recorded. The system learns from root causes to prevent future incidents.",
    "duma.step.memory.detail": "Record: Photo evidence and savings saved",
    "duma.footer.quote": "\"Duma translates numbers into daily operational tasks.\"",
    "duma.footer.priority": "Automatic prioritization",
    "duma.footer.agent": "24/7 Agent over Sidón",
    "duma.footer.error": "Zero manual error margin",

    "hero.dashboard.status1": "Operation on standard",
    "hero.dashboard.status2": "Energy under control",
    "hero.dashboard.status3": "Risks prevented",
    "hero.dashboard.status4": "Audit completed today",

    // Stats
    "stats.title1": "Results that ",
    "stats.title2": "Transform",
    "stats.subtitle": "Real metrics from clients who have implemented SIDÓN in their operations",
    "stats.energy.label": "Energy Savings",
    "stats.energy.description": "Reduction in electrical consumption through intelligent IoT monitoring",
    "stats.productivity.label": "Productivity Increase",
    "stats.productivity.description": "Improvement in operational efficiency with automated audits",
    "stats.operation.label": "Days of Reliable Operation",
    "stats.operation.description": "Guaranteed availability with 24/7 technical support",

    // Solutions
    "solutions.badge": "Modules",
    "solutions.title1": "Comprehensive Solutions for your ",
    "solutions.title2": "Operation",
    "solutions.subtitle": "Each module integrates perfectly to create a complete operational intelligence ecosystem",
    "solutions.learnMore": "Learn more",
    "solutions.sense.subtitle": "Intelligent Monitoring",
    "solutions.sense.title": "Sense IoT",
    "solutions.sense.description": "Real-time device control and monitoring. Temperature, energy, humidity sensors and more to optimize your operations.",
    "solutions.sense.feature1": "Real-time alerts",
    "solutions.sense.feature2": "Custom dashboards",
    "solutions.sense.feature3": "Integration with existing equipment",
    "solutions.audits.subtitle": "AI CCTV & Evidence",
    "solutions.audits.title": "Smart Audits",
    "solutions.audits.description": "Automated audits with artificial intelligence. Generate digital evidence for compliance and continuous improvement.",
    "solutions.audits.feature1": "AI visual recognition",
    "solutions.audits.feature2": "Automatic reports",
    "solutions.audits.feature3": "Photographic evidence",
    "solutions.mantiz.subtitle": "Maintenance Management",
    "solutions.mantiz.title": "Mantiz",
    "solutions.mantiz.description": "Complete system for preventive and corrective maintenance management. Reduce downtime and extend equipment lifespan.",
    "solutions.mantiz.feature1": "Digital work orders",
    "solutions.mantiz.feature2": "Preventive calendar",
    "solutions.mantiz.feature3": "Asset history",
    "solutions.citas.subtitle": "QR Access Control",
    "solutions.citas.title": "Citas",
    "solutions.citas.description": "Visitor and supplier management with QR codes. Record entries, exits, and generate attendance reports.",
    "solutions.citas.feature1": "Contactless check-in",
    "solutions.citas.feature2": "Visitor registration",
    "solutions.citas.feature3": "Access reports",

    // Comparison
    "comparison.badge": "Transformation",
    "comparison.title1": "From Reactive to ",
    "comparison.title2": "Predictive",
    "comparison.subtitle": "Compare how SIDÓN transforms your operation from a traditional model to one based on data and artificial intelligence",
    "comparison.before.subtitle": "Reactive Model",
    "comparison.before.title": "Current Situation",
    "comparison.before.item1": "Manual and sporadic audits",
    "comparison.before.item2": "No digital evidence of processes",
    "comparison.before.item3": "Late response to equipment failures",
    "comparison.before.item4": "Access control with physical logs",
    "comparison.before.item5": "Decisions based on perception",
    "comparison.before.item6": "Energy costs without monitoring",
    "comparison.after.subtitle": "Preventive & Digital Model",
    "comparison.after.title": "Sidón Enablement",
    "comparison.after.item1": "Automated audits with AI",
    "comparison.after.item2": "Real-time photographic and digital evidence",
    "comparison.after.item3": "Intelligent preventive maintenance",
    "comparison.after.item4": "Digital access control with QR",
    "comparison.after.item5": "Data-driven decisions",
    "comparison.after.item6": "Energy optimization with IoT",
    "comparison.recommended": "Recommended",
    "comparison.cta": "Start Transformation",
    "comparison.metrics.costs": "Op. Costs",
    "comparison.metrics.downtime": "Downtime",
    "comparison.metrics.efficiency": "Efficiency",
    "comparison.trend.negative": "Negative trend",
    "comparison.trend.positive": "Positive ROI confirmed",

    // Support
    "support.badge": "Strategic Support",
    "support.title1": "Your success is our ",
    "support.title2": "priority",
    "support.description": "We don't just deliver a platform, we accompany you every step of your digital transformation with a team of experts dedicated to maximizing the value of your investment.",
    "support.csq.title": "Customer Success Manager",
    "support.csq.subtitle": "Exclusive SIDÓN methodology",
    "support.csq.description": "Our CSM program combines technology and human support to ensure each client achieves their operational transformation goals.",
    "support.feature1.title": "Customer Success Manager (CSM)",
    "support.feature1.description": "Team dedicated to ensuring your implementation success with clear metrics and continuous follow-up.",
    "support.feature2.title": "Help Desk",
    "support.feature2.description": "Technical support available based on your service needs to resolve any incident.",
    "support.feature3.title": "Guaranteed SLA",
    "support.feature3.description": "Committed response times with documented and measurable service levels.",
    "support.feature4.title": "Continuous Training",
    "support.feature4.description": "Training programs for your team that ensure complete platform adoption.",
    "support.feature5.title": "Proactive Communication",
    "support.feature5.description": "We keep you informed with periodic reports and continuous improvement recommendations.",
    "support.feature6.title": "Enterprise Security",
    "support.feature6.description": "Robust infrastructure with security certifications and automatic information backups.",

    // CSM Commitment
    "csq.badge": "Customer Success Manager",
    "csq.title1": "Our Commitment: ",
    "csq.title2": "Customer Success Manager",
    "csq.subtitle": "We're not just support, we're your operational consultants",
    "csq.quote": "We're not just support, we're your operational consultants",
    "csq.point1.title": "Personalized Configuration",
    "csq.point1.description": "We adapt the platform to your specific needs, configuring each module according to your operation's unique processes.",
    "csq.point2.title": "Guidance and Training",
    "csq.point2.description": "We guide you with simple and accessible language, ensuring your entire team masters the platform without complications.",
    "csq.point3.title": "Results Interpretation",
    "csq.point3.description": "We analyze your data and provide actionable insights to maximize the ROI of your technology investment.",
    "csq.footer": "Committed to your operational success from day one",

    // ROI Section
    "roi.heading": "Culture is what happens when the boss isn't around",
    "roi.subtitle": "SIDÓN doesn't just digitize, it generates measurable impact on your costs and team effectiveness.",
    "roi.energy.title": "Energy Savings",
    "roi.energy.description": "Direct reduction in A/C and lighting consumption through intelligent monitoring.",
    "roi.productivity.title": "Increased Productivity",
    "roi.productivity.description": "Optimization of supervision time and effective execution of daily processes.",
    "roi.csm.badge": "Human support that guarantees your success",
    "roi.activity.title": "Real-Time Activity",
    "roi.activity.1": "Audit completed by Supervisor at North Branch",
    "roi.activity.2": "Preventive maintenance validated via Mantiz",
    "roi.activity.3": "Temperature report approved - Central Plant",
    "roi.activity.4": "Safety checklist completed - South Warehouse",
    "roi.activity.5": "Equipment inspection completed - Industrial Zone",
    "roi.activity.time.1": "5 min ago",
    "roi.activity.time.2": "12 min ago",
    "roi.activity.time.3": "18 min ago",
    "roi.activity.time.4": "25 min ago",
    "roi.activity.time.5": "32 min ago",
    "roi.cta.title": "Sustainable Qualitative Impact",
    "roi.cta.description": "Lower staff turnover and faster decisions based on real data.",
    "roi.cta.button": "Calculate My Return",

    // CSM Commitment Section
    "csqSection.title": "Human Commitment: CSM",
    "csqSection.subtitle": "More than Software, a Partner in Your Operation",
    "csqSection.card1.title": "Strategic Consulting",
    "csqSection.card1.description": "We customize SIDÓN according to your operation's specific needs. We don't sell a generic product, we co-create the solution with you.",
    "csqSection.card2.title": "Human Support",
    "csqSection.card2.description": "We speak your operational team's language. Our consultants are in the field, not just behind a desk, ensuring real adoption.",
    "csqSection.card3.title": "Results Evolution",
    "csqSection.card3.description": "We interpret your data and convert it into concrete actions. We measure ROI with you and adjust the strategy in real-time.",
    "csqSection.closing": "Our presence is critical to maintain the reliability of your operation 365 days a year.",
    "csqSection.closing.highlight": "reliability of your operation",

    // Mantiz Timeline
    "mantiz.badge": "Maintenance Management",
    "mantiz.title": "Complete Service Cycle",
    "mantiz.subtitle": "We automate and control the entire technical incident response cycle",
    "mantiz.node1.title": "Incident Report",
    "mantiz.node1.description": "Employee detects and reports a technical failure from their smartphone in real-time.",
    "mantiz.node1.imageAlt": "Employee reporting failure from smartphone",
    "mantiz.node2.title": "Smart Assignment",
    "mantiz.node2.description": "The system automatically assigns the task to the available technician based on location and specialty.",
    "mantiz.node2.imageAlt": "Admin dashboard assigning task",
    "mantiz.node3.title": "Field Validation",
    "mantiz.node3.description": "Technician scans QR code to validate location and register work start.",
    "mantiz.node3.imageAlt": "Technician scanning QR code",
    "mantiz.node4.title": "Evidence-Based Closure",
    "mantiz.node4.description": "Repair is validated with before and after photographic evidence, closing the ticket.",
    "mantiz.node4.imageAlt": "Ticket closure screen with evidence",
    "mantiz.cta": "Learn About Mantiz",

    // CTA
    "cta.title": "Start your digital transformation today",
    "cta.description": "Schedule a personalized demo and discover how SIDÓN can optimize your business operations with artificial intelligence and real-time data.",
    "cta.demo": "Request Demo",
    "cta.call": "Call Now",

    // Footer
    "footer.tagline": "Business Intelligence for retail. We transform data into intelligent decisions.",
    "footer.solutions": "Solutions",
    "footer.company": "Company",
    "footer.support": "Support",
    "footer.aboutUs": "About Us",
    "footer.successCases": "Success Cases",
    "footer.blog": "Blog",
    "footer.careers": "Careers",
    "footer.helpCenter": "Help Center",
    "footer.documentation": "Documentation",
    "footer.api": "API",
    "footer.systemStatus": "System Status",
    "footer.ecosat.title": "A product of",
    "footer.ecosat.tagline": "Technology solutions for the retail industry since 2008.",
    "footer.copyright": "© 2026 SIDÓN by ECOSAT. All rights reserved.",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.cookies": "Cookies",

    // Sense IoT Page
    "sense.hero.badge": "Internet of Things (IoT)",
    "sense.hero.title1": "Intelligence that feels,",
    "sense.hero.title2": "Data that acts.",
    "sense.hero.description": "Sidón Sense connects your physical infrastructure with your digital strategy. High-precision industrial sensors that transform every corner of your operation into a source of savings and control.",
    "sense.hero.cta": "Start monitoring",

    "sense.bento.cold.title": "Critical Cold Control",
    "sense.bento.cold.desc": "24/7 monitoring of chambers and refrigerators. Avoid waste due to broken cold chains.",
    "sense.bento.energy.title": "Energy Management",
    "sense.bento.energy.desc": "Visualize consumption in real-time. Detect inefficient equipment and electrical leaks.",
    "sense.bento.ambient.title": "Environmental Variables",
    "sense.bento.ambient.desc": "Humidity, CO2, and VOCs. Guarantee optimal environments for customers and products.",
    "sense.bento.assets.title": "Asset Health",
    "sense.bento.assets.desc": "Motor vibration and current. Predict failures before they stop your operation.",

    "sense.workflow.title": "From Sensor to Decision",
    "sense.workflow.step1.title": "Precise Capture",
    "sense.workflow.step1.desc": "Plug & Play industrial sensors measure critical variables every second.",
    "sense.workflow.step2.title": "Secure Transmission",
    "sense.workflow.step2.desc": "Gateways with military encryption send data via 4G or LoRaWAN.",
    "sense.workflow.step3.title": "Sidón Cloud",
    "sense.workflow.step3.desc": "AI algorithms analyze trends and detect anomalies instantaneously.",
    "sense.workflow.step4.title": "Closed Loop",
    "sense.workflow.step4.desc": "If something fails, DUMA assigns the task to the technician and closes the cycle.",

    "sense.benefits.title": "Direct Impact on your Bottom-Line",
    "sense.benefits.1.title": "Waste Reduction",
    "sense.benefits.1.desc": "Up to 30% less product loss due to refrigeration failures.",
    "sense.benefits.2.title": "Energy Savings",
    "sense.benefits.2.desc": "Schedule optimization and ghost consumption detection (-15% bill).",
    "sense.benefits.3.title": "Regulatory Compliance",
    "sense.benefits.3.desc": "Automatic reports for regulatory entities.",

    // SmartAudits Page
    "audits.hero.badge": "Audit Management",
    "audits.hero.title1": "Real control of operational execution",
    "audits.hero.title2": "through intelligent audits",
    "audits.hero.description": "SmartAudits automates the management, execution, and supervision of audits through AI, reducing errors and increasing compliance.",
    "audits.hero.cta": "Request demo",
    "audits.hero.cta2": "See how it works",
    "audits.problem.title": "The end of reactive auditing",
    "audits.problem.desc": "Overcome the real pains of traditional supervision.",
    "audits.problem.1.title": "Manual Audits",
    "audits.problem.1.desc": "Predictable processes that don't reflect daily reality.",
    "audits.problem.2.title": "Lack of Evidence",
    "audits.problem.2.desc": "Reports without objective support or visual validation.",
    "audits.problem.3.title": "Slow Supervision",
    "audits.problem.3.desc": "Late reaction when the problem has already affected the operation.",
    "audits.problem.4.title": "Inconsistent Compliance",
    "audits.problem.4.desc": "Execution variability between different shifts or branches.",
    "audits.whatis.title": "What is SmartAudits?",
    "audits.whatis.subtitle": "Operational Discipline and Continuous Control",
    "audits.whatis.description": "An intelligent operational audit platform with AI-assisted task management to ensure excellence at every touchpoint.",
    "audits.features.title": "Next-Generation Capabilities",
    "audits.features.1.title": "Automatic Assignment",
    "audits.features.1.desc": "AI dynamically schedules tasks based on operational priorities.",
    "audits.features.2.title": "Random Execution",
    "audits.features.2.desc": "Eliminates predictability and ensures real and honest supervision.",
    "audits.features.3.title": "Visual Evidence",
    "audits.features.3.desc": "Image capture for each task with immediate validation.",
    "audits.features.4.title": "AI Analysis",
    "audits.features.4.desc": "AI automatically validates compliance by analyzing images.",
    "audits.workflow.title": "Intelligent Execution Flow",
    "audits.workflow.step1.title": "AI Assignment",
    "audits.workflow.step1.desc": "AI assigns and schedules audits intelligently and strategically.",
    "audits.workflow.step2.title": "Field Execution",
    "audits.workflow.step2.desc": "Staff executes assigned tasks guided by the platform.",
    "audits.workflow.step3.title": "Visual Evidence",
    "audits.workflow.step3.desc": "Objective visual evidence of each task performed is captured.",
    "audits.workflow.step4.title": "Validation and Decision",
    "audits.workflow.step4.desc": "AI analyzes compliance and supervisors make informed decisions.",
    "audits.benefits.title": "High-Impact Results",
    "audits.benefits.1.title": "Fewer Errors",
    "audits.benefits.1.desc": "Drastic reduction in failures through standardized processes.",
    "audits.benefits.2.title": "Total Objectivity",
    "audits.benefits.2.desc": "Audits based on data and objective visual evidence.",
    "audits.benefits.3.title": "Time Savings",
    "audits.benefits.3.desc": "Radical optimization of supervision and reporting time.",
    "audits.footer.tagline": "With SmartAudits, innovation becomes efficiency.",
    "audits.footer.cta1": "Automate. Simplify. Advance.",
    "audits.footer.demo": "Request demo",
    "audits.footer.expert": "Contact an advisor",

    // Smart Citas Page
    "citas.hero.badge": "Access Management",
    "citas.hero.title1": "Comprehensive Platform for",
    "citas.hero.title2": "Appointments & Visitor Control",
    "citas.hero.description": "Optimize your reception to reduce operating costs and boost productivity. Smart Citas automates access, notifications, and validations, eliminating bottlenecks from a single platform.",
    "citas.hero.cta": "Request demo",
    "citas.hero.cta2": "Learn about the solution",

    "citas.problem.title": "Reception chaos costs more than you think.",
    "citas.problem.item1.title": "Manual Registration",
    "citas.problem.item1.desc": "Paper-based processes, disorganized and without real validation.",
    "citas.problem.item2.title": "Lack of Traceability",
    "citas.problem.item2.desc": "Impossible to audit who entered, at what time, and for what reason.",
    "citas.problem.item3.title": "Slow Reception",
    "citas.problem.item3.desc": "Bottlenecks that affect corporate image and productivity.",
    "citas.problem.item4.title": "Security Risks",
    "citas.problem.item4.desc": "Vulnerability to unauthorized entries and lack of policy control.",

    "citas.about.title": "What is Smart Citas?",
    "citas.about.desc1": "It is Sidón's specialized module designed to optimize and automate the complete visitor registration and control cycle.",
    "citas.about.desc2": "From the initial appointment to validated entry, Smart Citas ensures that every person entering your facilities is authorized, registered, and monitored.",

    "citas.features.title": "Key Features",
    "citas.features.1.title": "Schedule Management",
    "citas.features.1.desc": "Create appointments by visitor, reason, and specific visiting area.",
    "citas.features.2.title": "QR Notification",
    "citas.features.2.desc": "Automatic delivery of personalized QR codes via email and WhatsApp.",
    "citas.features.3.title": "Seamless Integration",
    "citas.features.3.desc": "Native synchronization with Google Calendar for a unified agenda.",
    "citas.features.4.title": "Arrival Validation",
    "citas.features.4.desc": "Fast QR check-in with date, time, and area validation. Immediate notification to the host.",

    "citas.security.title": "Executive-Level Control and Security",
    "citas.security.desc": "We don't just register visits; we protect your operation through compliance and privacy standards.",
    "citas.security.item1": "Digital registration with image and ID capture.",
    "citas.security.item2": "Detailed visit history by person and frequency.",
    "citas.security.item3": "Dynamic access control aligned with internal policies.",

    "citas.benefits.title": "Direct Impact: Lower Costs, Higher Productivity",
    "citas.benefits.1.title": "Orderly & Profitable Access",
    "citas.benefits.1.desc": "Eliminate queues and clutter at entry points.",
    "citas.benefits.2.title": "Real Communication",
    "citas.benefits.2.desc": "Hosts notified instantly, ready to receive their guest.",
    "citas.benefits.3.title": "Full Traceability",
    "citas.benefits.3.desc": "Absolute control of people flow in real-time.",

    "citas.footer.tagline": "ORDER, SECURITY AND CONTROL",
    "citas.footer.cta1": "Control from the first contact.",
    "citas.footer.demo": "Request demo",
    "citas.footer.expert": "Contact an advisor",

    // Contact Form
    "contact.title": "Contact Sales",
    "contact.subtitle": "Ready to transform your operations? Our sales team is here to help.",
    "contact.name": "Full name",
    "contact.email": "Email address",
    "contact.company": "Company",
    "contact.message": "Message",
    "contact.submit": "Send message",
    "contact.sending": "Sending...",
    "contact.success": "Message sent successfully. We will get back to you soon.",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("es")

  const t = useCallback(
    (key: string): string => {
      return translations[language][key] || key
    },
    [language]
  )

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
