"use client"

import { createContext, useContext, useState, useCallback, type ReactNode } from "react"

export type Language = "es" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Header
    "nav.solutions": "Soluciones",
    "nav.modules": "Módulos",
    "nav.roi": "ROI",
    "nav.contact": "Contacto",
    "nav.requestDemo": "Solicitar Demo",
    "nav.modules.all": "Ver todos los módulos",
    "nav.modules.sense": "Sense IOT",
    "nav.modules.mantenimiento": "Gestión de Mantenimiento",
    "nav.modules.duma": "DUMA Agente AI",

    // Hero
    "hero.badge": "Business Intelligence para CEOs",
    "hero.title1": "Toma control real de tu operación.",
    "hero.title2": "Incluso cuando no estás.",
    "hero.description": "Sidón acompaña a CEOs a reducir costos, elevar productividad y mejorar el desempeño operativo mediante experiencia real, procesos claros y AI aplicada.",
    "hero.cta.primary": "Ver cómo Sidón genera ahorro y control",
    "hero.cta.secondary": "Solicitar demo",
    "hero.impact.title": "Impacto Ejecutivo",
    "hero.impact.savings.title": "Ahorro operativo",
    "hero.impact.savings.description": "Gestión energética inteligente, menos mermas y reprocesos.",
    "hero.impact.productivity.title": "Productividad",
    "hero.impact.productivity.description": "Equipos alineados, menos supervisión directa.",
    "hero.impact.performance.title": "Desempeño operativo",
    "hero.impact.performance.description": "Auditoría continua, evidencia y mejora diaria.",
    "hero.impact.culture.title": "Cultura",
    "hero.impact.culture.description": "Disciplina operativa sostenida por el sistema Sidón.",
    "hero.trust.title": "Implementación acompañada · Solución llave en mano · Evidencia diaria",
    "hero.social.proof": "+350 sucursales · +3,000 personas · Operación real",

    // Duma Section
    "duma.badge": "Agente Operativo",
    "duma.title1": "DUMA: No es otro dashboard,",
    "duma.title2": "es tu cerebro operativo.",
    "duma.description": "Mientras un dashboard normal te muestra que algo falló ayer, DUMA actúa hoy. Traduce la \"data dura\" de Sidón en acciones concretas para tu staff, eliminando la brecha entre el reporte y la resolución.",
    "duma.hours": "Horas recuperadas al día",
    "duma.traceability": "Trazabilidad de acciones",
    "duma.fatigue.title": "La \"Fatiga de Datos\" hoy:",
    "duma.fatigue.search": "Buscar información",
    "duma.fatigue.consolidate": "Consolidar datos",
    "duma.fatigue.format": "Dar formato",
    "duma.fatigue.report": "Generar reportes",
    "duma.fatigue.quote": "\"Los coordinadores pierden el 50% de su jornada en reporteo manual\"",
    "duma.fatigue.solution": "DUMA elimina el Proceso Manual al 100%",
    "duma.loop.title": "Ejecución inmediata con Closed Loop",
    "duma.loop.description": "Del 'Insight' a la 'Acción' en un clic. Duma no reemplaza a Sidón; lo potencia convirtiendo la inteligencia en ejecución.",
    "duma.step.insight.title": "Insight",
    "duma.step.insight.desc": "Duma detecta el problema analizando múltiples fuentes (SAP, Excel, Sidón) en milisegundos.",
    "duma.step.insight.detail": "Detecta: Venta -15% en Sucursal Norte",
    "duma.step.action.title": "Acción",
    "duma.step.action.desc": "Convierte el dato en una tarea operativa directa sin que el CEO tenga que intervenir.",
    "duma.step.action.detail": "Tarea: 'Revisar inventario de perecederos'",
    "duma.step.resolution.title": "Resolución",
    "duma.step.resolution.desc": "El staff en tienda recibe la instrucción y resuelve en campo, cerrando la brecha operativa.",
    "duma.step.resolution.detail": "Estado: Ejecutado por Gerente de Tienda",
    "duma.step.memory.title": "Memoria",
    "duma.step.memory.desc": "Todo queda registrado. El sistema aprende de las causas raíz para evitar incidencias futuras.",
    "duma.step.memory.detail": "Registro: Evidencia fotográfica y ahorro guardado",
    "duma.footer.quote": "\"Duma traduce los números en tareas operativas diarias.\"",
    "duma.footer.priority": "Priorización automática",
    "duma.footer.agent": "Agente 24/7 sobre Sidón",
    "duma.footer.error": "Cero margen de error manual",

    "hero.dashboard.status1": "Operación en estándar",
    "hero.dashboard.status2": "Energía bajo control",
    "hero.dashboard.status3": "Riesgos prevenidos",
    "hero.dashboard.status4": "Auditoría completada hoy",

    // Stats
    "stats.title1": "Resultados que ",
    "stats.title2": "Transforman",
    "stats.subtitle": "Métricas reales de clientes que han implementado SIDÓN en sus operaciones",
    "stats.energy.label": "Ahorro Energético",
    "stats.energy.description": "Reducción en consumo eléctrico mediante monitoreo IoT inteligente",
    "stats.productivity.label": "Incremento en Productividad",
    "stats.productivity.description": "Mejora en eficiencia operativa con auditorías automatizadas",
    "stats.operation.label": "Días de Operación Confiable",
    "stats.operation.description": "Disponibilidad garantizada con soporte técnico 24/7",

    // Solutions
    "solutions.badge": "Módulos",
    "solutions.title1": "Soluciones Integrales para tu ",
    "solutions.title2": "Operación",
    "solutions.subtitle": "Cada módulo se integra perfectamente para crear un ecosistema completo de inteligencia operativa",
    "solutions.learnMore": "Conocer más",
    "solutions.sense.subtitle": "Monitoreo Inteligente",
    "solutions.sense.title": "Sense IoT",
    "solutions.sense.description": "Control y monitoreo de dispositivos en tiempo real. Sensores de temperatura, energía, humedad y más para optimizar tus operaciones.",
    "solutions.sense.feature1": "Alertas en tiempo real",
    "solutions.sense.feature2": "Dashboards personalizados",
    "solutions.sense.feature3": "Integración con equipos existentes",
    "solutions.audits.subtitle": "AI CCTV & Evidencia",
    "solutions.audits.title": "Smart Audits",
    "solutions.audits.description": "Auditorías automatizadas con inteligencia artificial. Genera evidencia digital para cumplimiento y mejora continua.",
    "solutions.audits.feature1": "Reconocimiento visual AI",
    "solutions.audits.feature2": "Reportes automáticos",
    "solutions.audits.feature3": "Evidencia fotográfica",
    "solutions.mantiz.subtitle": "Gestión de Mantenimiento",
    "solutions.mantiz.title": "Mantiz",
    "solutions.mantiz.description": "Sistema completo para la gestión preventiva y correctiva de mantenimientos. Reduce tiempos de paro y extiende la vida útil de equipos.",
    "solutions.mantiz.feature1": "Órdenes de trabajo digitales",
    "solutions.mantiz.feature2": "Calendario preventivo",
    "solutions.mantiz.feature3": "Historial de activos",
    "solutions.citas.subtitle": "Control de Acceso QR",
    "solutions.citas.title": "Citas",
    "solutions.citas.description": "Gestión de visitantes y proveedores con códigos QR. Registra entradas, salidas y genera reportes de asistencia.",
    "solutions.citas.feature1": "Check-in sin contacto",
    "solutions.citas.feature2": "Registro de visitantes",
    "solutions.citas.feature3": "Reportes de acceso",

    // Comparison
    "comparison.badge": "Transformación",
    "comparison.title1": "De Reactivo a ",
    "comparison.title2": "Predictivo",
    "comparison.subtitle": "Compara cómo SIDÓN transforma tu operación de un modelo tradicional a uno basado en datos e inteligencia artificial",
    "comparison.before.subtitle": "Modelo Reactivo",
    "comparison.before.title": "Situación Actual",
    "comparison.before.item1": "Auditorías manuales y esporádicas",
    "comparison.before.item2": "Sin evidencia digital de procesos",
    "comparison.before.item3": "Reacción tardía a fallas de equipos",
    "comparison.before.item4": "Control de acceso con bitácoras físicas",
    "comparison.before.item5": "Decisiones basadas en percepción",
    "comparison.before.item6": "Costos energéticos sin monitoreo",
    "comparison.after.subtitle": "Modelo Preventivo & Digital",
    "comparison.after.title": "Habilitación Sidón",
    "comparison.after.item1": "Auditorías automatizadas con AI",
    "comparison.after.item2": "Evidencia fotográfica y digital en tiempo real",
    "comparison.after.item3": "Mantenimiento preventivo inteligente",
    "comparison.after.item4": "Control de acceso digital con QR",
    "comparison.after.item5": "Decisiones basadas en datos",
    "comparison.after.item6": "Optimización energética con IoT",
    "comparison.recommended": "Recomendado",
    "comparison.cta": "Comenzar Transformación",
    "comparison.metrics.costs": "Costos Op.",
    "comparison.metrics.downtime": "Tiempo Paro",
    "comparison.metrics.efficiency": "Eficiencia",
    "comparison.trend.negative": "Tendencia negativa",
    "comparison.trend.positive": "ROI positivo confirmado",

    // Support
    "support.badge": "Soporte Estratégico",
    "support.title1": "Tu éxito es nuestra ",
    "support.title2": "prioridad",
    "support.description": "No solo te entregamos una plataforma, te acompañamos en cada paso de tu transformación digital con un equipo de expertos dedicados a maximizar el valor de tu inversión.",
    "support.csq.title": "Customer Success Quality",
    "support.csq.subtitle": "Metodología exclusiva SIDÓN",
    "support.csq.description": "Nuestro programa CSQ combina tecnología y acompañamiento humano para garantizar que cada cliente alcance sus objetivos de transformación operativa.",
    "support.feature1.title": "Customer Success Quality (CSQ)",
    "support.feature1.description": "Equipo dedicado a garantizar el éxito de tu implementación con métricas claras y seguimiento continuo.",
    "support.feature2.title": "Mesa de Ayuda 24/7",
    "support.feature2.description": "Soporte técnico disponible las 24 horas del día, los 365 días del año para resolver cualquier incidencia.",
    "support.feature3.title": "SLA Garantizado",
    "support.feature3.description": "Tiempos de respuesta comprometidos con niveles de servicio documentados y medibles.",
    "support.feature4.title": "Capacitación Continua",
    "support.feature4.description": "Programas de entrenamiento para tu equipo que aseguran la adopción completa de la plataforma.",
    "support.feature5.title": "Comunicación Proactiva",
    "support.feature5.description": "Te mantenemos informado con reportes periódicos y recomendaciones de mejora continua.",
    "support.feature6.title": "Seguridad Empresarial",
    "support.feature6.description": "Infraestructura robusta con certificaciones de seguridad y respaldos automáticos de información.",

    // CSQ Commitment
    "csq.badge": "Customer Success Quality",
    "csq.title1": "Nuestro Compromiso: ",
    "csq.title2": "Customer Success Quality",
    "csq.subtitle": "No somos solo soporte, somos tus consultores operativos",
    "csq.quote": "No somos solo soporte, somos tus consultores operativos",
    "csq.point1.title": "Configuración Personalizada",
    "csq.point1.description": "Adaptamos la plataforma a tus necesidades específicas, configurando cada módulo según los procesos únicos de tu operación.",
    "csq.point2.title": "Acompañamiento y Capacitación",
    "csq.point2.description": "Te guiamos con un lenguaje sencillo y accesible, asegurando que todo tu equipo domine la plataforma sin complicaciones.",
    "csq.point3.title": "Interpretación de Resultados",
    "csq.point3.description": "Analizamos tus datos y te brindamos insights accionables para maximizar el ROI de tu inversión tecnológica.",
    "csq.footer": "Comprometidos con tu éxito operativo desde el día uno",

    // ROI Section
    "roi.heading": "La cultura es lo que sucede cuando el jefe no está",
    "roi.subtitle": "SIDÓN no solo digitaliza, genera un impacto medible en los costos y la efectividad de tu equipo.",
    "roi.energy.title": "Ahorro Energético",
    "roi.energy.description": "Reducción directa en el consumo de A/C e iluminación mediante monitoreo inteligente.",
    "roi.productivity.title": "Mayor Productividad",
    "roi.productivity.description": "Optimización del tiempo de supervisión y ejecución efectiva de procesos diarios.",
    "roi.csq.badge": "Acompañamiento humano que garantiza tu éxito",
    "roi.activity.title": "Actividad en Tiempo Real",
    "roi.activity.1": "Auditoría completada por Supervisor en Sucursal Norte",
    "roi.activity.2": "Mantenimiento preventivo validado vía Mantiz",
    "roi.activity.3": "Reporte de temperatura aprobado - Planta Central",
    "roi.activity.4": "Checklist de seguridad completado - Almacén Sur",
    "roi.activity.5": "Inspección de equipos finalizada - Zona Industrial",
    "roi.activity.time.1": "Hace 5 min",
    "roi.activity.time.2": "Hace 12 min",
    "roi.activity.time.3": "Hace 18 min",
    "roi.activity.time.4": "Hace 25 min",
    "roi.activity.time.5": "Hace 32 min",
    "roi.cta.title": "Impacto Cualitativo Sostenible",
    "roi.cta.description": "Menor rotación de personal y decisiones más rápidas basadas en datos reales.",
    "roi.cta.button": "Calcular mi Retorno",

    // CSQ Commitment Section
    "csqSection.title": "Compromiso Humano: CSQ",
    "csqSection.subtitle": "Más que Software, un Socio en tu Operación",
    "csqSection.card1.title": "Consultoría Estratégica",
    "csqSection.card1.description": "Personalizamos SIDÓN según las necesidades específicas de tu operación. No vendemos un producto genérico, co-creamos la solución contigo.",
    "csqSection.card2.title": "Acompañamiento Humano",
    "csqSection.card2.description": "Hablamos el lenguaje de tu equipo operativo. Nuestros consultores están en campo, no solo detrás de un escritorio, garantizando adopción real.",
    "csqSection.card3.title": "Evolución de Resultados",
    "csqSection.card3.description": "Interpretamos tus datos y los convertimos en acciones concretas. Medimos el ROI contigo y ajustamos la estrategia en tiempo real.",
    "csqSection.closing": "Nuestra presencia es crítica para mantener la confiabilidad de tu operación los 365 días del año.",
    "csqSection.closing.highlight": "confiabilidad de tu operación",

    // Mantiz Timeline
    "mantiz.badge": "Gestión de Mantenimiento",
    "mantiz.title": "Ciclo Completo de Atención",
    "mantiz.subtitle": "Automatizamos y controlamos todo el ciclo de atención de incidencias técnicas",
    "mantiz.node1.title": "Reporte de Incidencia",
    "mantiz.node1.description": "El empleado detecta y reporta una falla técnica desde su smartphone en tiempo real.",
    "mantiz.node1.imageAlt": "Empleado reportando falla desde smartphone",
    "mantiz.node2.title": "Asignación Inteligente",
    "mantiz.node2.description": "El sistema asigna automáticamente la tarea al técnico disponible según ubicación y especialidad.",
    "mantiz.node2.imageAlt": "Dashboard administrativo asignando tarea",
    "mantiz.node3.title": "Validación en Campo",
    "mantiz.node3.description": "El técnico escanea código QR para validar su ubicación y registrar inicio de trabajo.",
    "mantiz.node3.imageAlt": "Técnico escaneando código QR",
    "mantiz.node4.title": "Cierre con Evidencia",
    "mantiz.node4.description": "Se valida la reparación con evidencia fotográfica antes y después, cerrando el ticket.",
    "mantiz.node4.imageAlt": "Pantalla de cierre de ticket con evidencia",
    "mantiz.cta": "Conocer Mantiz",

    // CTA
    "cta.title": "Comienza tu transformación digital hoy",
    "cta.description": "Agenda una demostración personalizada y descubre cómo SIDÓN puede optimizar las operaciones de tu negocio con inteligencia artificial y datos en tiempo real.",
    "cta.demo": "Solicitar Demo Gratuita",
    "cta.call": "Llamar Ahora",

    // Footer
    "footer.tagline": "Business Intelligence para retail. Transformamos datos en decisiones inteligentes.",
    "footer.solutions": "Soluciones",
    "footer.company": "Empresa",
    "footer.support": "Soporte",
    "footer.aboutUs": "Nosotros",
    "footer.successCases": "Casos de Éxito",
    "footer.blog": "Blog",
    "footer.careers": "Carreras",
    "footer.helpCenter": "Centro de Ayuda",
    "footer.documentation": "Documentación",
    "footer.api": "API",
    "footer.systemStatus": "Estado del Sistema",
    "footer.ecosat.title": "Una empresa de",
    "footer.ecosat.tagline": "Soluciones tecnológicas para la industria retail desde 2008.",
    "footer.copyright": "© 2026 SIDÓN by ECOSAT. Todos los derechos reservados.",
    "footer.privacy": "Privacidad",
    "footer.terms": "Términos",
    "footer.cookies": "Cookies",

    // Sense IoT Page
    "sense.hero.badge": "Internet de las Cosas (IoT)",
    "sense.hero.title1": "Inteligencia que siente,",
    "sense.hero.title2": "Datos que actúan.",
    "sense.hero.description": "Sidón Sense conecta tu infraestructura física con tu estrategia digital. Sensores industriales de alta precisión que transforman cada rincón de tu operación en una fuente de ahorro y control.",
    "sense.hero.cta": "Comenzar monitoreo",

    "sense.bento.cold.title": "Control de Frío Crítico",
    "sense.bento.cold.desc": "Monitoreo 24/7 de cámaras y refrigeradores. Evita mermas por cadena de frío rota.",
    "sense.bento.energy.title": "Gestión de Energía",
    "sense.bento.energy.desc": "Visualiza el consumo en tiempo real. Detecta equipos ineficientes y fugas eléctricas.",
    "sense.bento.ambient.title": "Variables Ambientales",
    "sense.bento.ambient.desc": "Humedad, CO2 y VOCs. Garantiza ambientes óptimos para clientes y productos.",
    "sense.bento.assets.title": "Salud de Activos",
    "sense.bento.assets.desc": "Vibración y corriente en motores. Predice fallas antes de que detengan tu operación.",

    "sense.workflow.title": "Del Sensor a la Decisión",
    "sense.workflow.step1.title": "Captura Precisa",
    "sense.workflow.step1.desc": "Sensores industriales Plug & Play miden variables críticas cada segundo.",
    "sense.workflow.step2.title": "Transmisión Segura",
    "sense.workflow.step2.desc": "Gateways con encriptación militar envían la data vía 4G o LoRaWAN.",
    "sense.workflow.step3.title": "Nube Sidón",
    "sense.workflow.step3.desc": "Algoritmos de AI analizan tendencias y detectan anomalías instantáneamente.",
    "sense.workflow.step4.title": "Closed Loop",
    "sense.workflow.step4.desc": "Si algo falla, DUMA asigna la tarea al técnico y cierra el ciclo.",

    "sense.benefits.title": "Impacto Directo en tu Bottom-Line",
    "sense.benefits.1.title": "Reducción de Mermas",
    "sense.benefits.1.desc": "Hasta un 30% menos de pérdida de producto por fallas en refrigeración.",
    "sense.benefits.2.title": "Ahorro Energético",
    "sense.benefits.2.desc": "Optimización de horarios y detección de consumos fantasma (-15% factura).",
    "sense.benefits.3.title": "Cumplimiento Normativo",
    "sense.benefits.3.desc": "Reportes automáticos para entidades regulatorias.",
  },
  en: {
    // Header
    "nav.solutions": "Solutions",
    "nav.modules": "Modules",
    "nav.roi": "ROI",
    "nav.contact": "Contact",
    "nav.requestDemo": "Request Demo",
    "nav.modules.all": "See all modules",
    "nav.modules.sense": "Sense IOT",
    "nav.modules.mantenimiento": "Maintenance Management",
    "nav.modules.duma": "DUMA AI Agent",

    // Hero
    "hero.badge": "Business Intelligence for CEOs",
    "hero.title1": "Take real control of your operation.",
    "hero.title2": "Even when you're not there.",
    "hero.description": "Sidón helps CEOs reduce costs, increase productivity, and improve operational performance through real experience, clear processes, and applied AI.",
    "hero.cta.primary": "See how Sidón generates savings and control",
    "hero.cta.secondary": "Request demo",
    "hero.impact.title": "Executive Impact",
    "hero.impact.savings.title": "Operational savings",
    "hero.impact.savings.description": "Intelligent energy management, less waste and rework.",
    "hero.impact.productivity.title": "Productivity",
    "hero.impact.productivity.description": "Aligned teams, less direct supervision.",
    "hero.impact.performance.title": "Operational performance",
    "hero.impact.performance.description": "Continuous audit, evidence and daily improvement.",
    "hero.impact.culture.title": "Culture",
    "hero.impact.culture.description": "Operational discipline sustained by the Sidón system.",
    "hero.trust.title": "Guided implementation · Turnkey solution · Daily evidence",
    "hero.social.proof": "+350 branches · +3,000 people · Real operation",

    // Duma Section
    "duma.badge": "Operational Agent",
    "duma.title1": "DUMA: Not another dashboard,",
    "duma.title2": "is your operational brain.",
    "duma.description": "While a normal dashboard shows you what failed yesterday, DUMA acts today. It translates Sidón's \"hard data\" into concrete actions for your staff, eliminating the gap between reporting and resolution.",
    "duma.hours": "Hours recovered daily",
    "duma.traceability": "Traceability of actions",
    "duma.fatigue.title": "Today's \"Data Fatigue\":",
    "duma.fatigue.search": "Search information",
    "duma.fatigue.consolidate": "Consolidate data",
    "duma.fatigue.format": "Format data",
    "duma.fatigue.report": "Generate reports",
    "duma.fatigue.quote": "\"Coordinators lose 50% of their workday in manual reporting\"",
    "duma.fatigue.solution": "DUMA eliminates Manual Process by 100%",
    "duma.loop.title": "Immediate execution with Closed Loop",
    "duma.loop.description": "From 'Insight' to 'Action' in one click. Duma doesn't replace Sidón; it enhances it by turning intelligence into execution.",
    "duma.step.insight.title": "Insight",
    "duma.step.insight.desc": "Duma detects the problem by analyzing multiple sources (SAP, Excel, Sidón) in milliseconds.",
    "duma.step.insight.detail": "Detects: Sales -15% in North Branch",
    "duma.step.action.title": "Action",
    "duma.step.action.desc": "Converts data into a direct operational task without CEO intervention.",
    "duma.step.action.detail": "Task: 'Check perishable inventory'",
    "duma.step.resolution.title": "Resolution",
    "duma.step.resolution.desc": "Store staff receives instruction and resolves in the field, closing the operational gap.",
    "duma.step.resolution.detail": "Status: Executed by Store Manager",
    "duma.step.memory.title": "Memory",
    "duma.step.memory.desc": "Everything is recorded. The system learns from root causes to prevent future incidents.",
    "duma.step.memory.detail": "Record: Photo evidence and savings saved",
    "duma.footer.quote": "\"Duma translates numbers into daily operational tasks.\"",
    "duma.footer.priority": "Automatic prioritization",
    "duma.footer.agent": "24/7 Agent over Sidón",
    "duma.footer.error": "Zero manual error margin",

    "hero.dashboard.status1": "Operation on standard",
    "hero.dashboard.status2": "Energy under control",
    "hero.dashboard.status3": "Risks prevented",
    "hero.dashboard.status4": "Audit completed today",

    // Stats
    "stats.title1": "Results that ",
    "stats.title2": "Transform",
    "stats.subtitle": "Real metrics from clients who have implemented SIDÓN in their operations",
    "stats.energy.label": "Energy Savings",
    "stats.energy.description": "Reduction in electrical consumption through intelligent IoT monitoring",
    "stats.productivity.label": "Productivity Increase",
    "stats.productivity.description": "Improvement in operational efficiency with automated audits",
    "stats.operation.label": "Days of Reliable Operation",
    "stats.operation.description": "Guaranteed availability with 24/7 technical support",

    // Solutions
    "solutions.badge": "Modules",
    "solutions.title1": "Comprehensive Solutions for your ",
    "solutions.title2": "Operation",
    "solutions.subtitle": "Each module integrates perfectly to create a complete operational intelligence ecosystem",
    "solutions.learnMore": "Learn more",
    "solutions.sense.subtitle": "Intelligent Monitoring",
    "solutions.sense.title": "Sense IoT",
    "solutions.sense.description": "Real-time device control and monitoring. Temperature, energy, humidity sensors and more to optimize your operations.",
    "solutions.sense.feature1": "Real-time alerts",
    "solutions.sense.feature2": "Custom dashboards",
    "solutions.sense.feature3": "Integration with existing equipment",
    "solutions.audits.subtitle": "AI CCTV & Evidence",
    "solutions.audits.title": "Smart Audits",
    "solutions.audits.description": "Automated audits with artificial intelligence. Generate digital evidence for compliance and continuous improvement.",
    "solutions.audits.feature1": "AI visual recognition",
    "solutions.audits.feature2": "Automatic reports",
    "solutions.audits.feature3": "Photographic evidence",
    "solutions.mantiz.subtitle": "Maintenance Management",
    "solutions.mantiz.title": "Mantiz",
    "solutions.mantiz.description": "Complete system for preventive and corrective maintenance management. Reduce downtime and extend equipment lifespan.",
    "solutions.mantiz.feature1": "Digital work orders",
    "solutions.mantiz.feature2": "Preventive calendar",
    "solutions.mantiz.feature3": "Asset history",
    "solutions.citas.subtitle": "QR Access Control",
    "solutions.citas.title": "Citas",
    "solutions.citas.description": "Visitor and supplier management with QR codes. Record entries, exits, and generate attendance reports.",
    "solutions.citas.feature1": "Contactless check-in",
    "solutions.citas.feature2": "Visitor registration",
    "solutions.citas.feature3": "Access reports",

    // Comparison
    "comparison.badge": "Transformation",
    "comparison.title1": "From Reactive to ",
    "comparison.title2": "Predictive",
    "comparison.subtitle": "Compare how SIDÓN transforms your operation from a traditional model to one based on data and artificial intelligence",
    "comparison.before.subtitle": "Reactive Model",
    "comparison.before.title": "Current Situation",
    "comparison.before.item1": "Manual and sporadic audits",
    "comparison.before.item2": "No digital evidence of processes",
    "comparison.before.item3": "Late response to equipment failures",
    "comparison.before.item4": "Access control with physical logs",
    "comparison.before.item5": "Decisions based on perception",
    "comparison.before.item6": "Energy costs without monitoring",
    "comparison.after.subtitle": "Preventive & Digital Model",
    "comparison.after.title": "Sidón Enablement",
    "comparison.after.item1": "Automated audits with AI",
    "comparison.after.item2": "Real-time photographic and digital evidence",
    "comparison.after.item3": "Intelligent preventive maintenance",
    "comparison.after.item4": "Digital access control with QR",
    "comparison.after.item5": "Data-driven decisions",
    "comparison.after.item6": "Energy optimization with IoT",
    "comparison.recommended": "Recommended",
    "comparison.cta": "Start Transformation",
    "comparison.metrics.costs": "Op. Costs",
    "comparison.metrics.downtime": "Downtime",
    "comparison.metrics.efficiency": "Efficiency",
    "comparison.trend.negative": "Negative trend",
    "comparison.trend.positive": "Positive ROI confirmed",

    // Support
    "support.badge": "Strategic Support",
    "support.title1": "Your success is our ",
    "support.title2": "priority",
    "support.description": "We don't just deliver a platform, we accompany you every step of your digital transformation with a team of experts dedicated to maximizing the value of your investment.",
    "support.csq.title": "Customer Success Quality",
    "support.csq.subtitle": "Exclusive SIDÓN methodology",
    "support.csq.description": "Our CSQ program combines technology and human support to ensure each client achieves their operational transformation goals.",
    "support.feature1.title": "Customer Success Quality (CSQ)",
    "support.feature1.description": "Team dedicated to ensuring your implementation success with clear metrics and continuous follow-up.",
    "support.feature2.title": "24/7 Help Desk",
    "support.feature2.description": "Technical support available 24 hours a day, 365 days a year to resolve any incident.",
    "support.feature3.title": "Guaranteed SLA",
    "support.feature3.description": "Committed response times with documented and measurable service levels.",
    "support.feature4.title": "Continuous Training",
    "support.feature4.description": "Training programs for your team that ensure complete platform adoption.",
    "support.feature5.title": "Proactive Communication",
    "support.feature5.description": "We keep you informed with periodic reports and continuous improvement recommendations.",
    "support.feature6.title": "Enterprise Security",
    "support.feature6.description": "Robust infrastructure with security certifications and automatic information backups.",

    // CSQ Commitment
    "csq.badge": "Customer Success Quality",
    "csq.title1": "Our Commitment: ",
    "csq.title2": "Customer Success Quality",
    "csq.subtitle": "We're not just support, we're your operational consultants",
    "csq.quote": "We're not just support, we're your operational consultants",
    "csq.point1.title": "Personalized Configuration",
    "csq.point1.description": "We adapt the platform to your specific needs, configuring each module according to your operation's unique processes.",
    "csq.point2.title": "Guidance and Training",
    "csq.point2.description": "We guide you with simple and accessible language, ensuring your entire team masters the platform without complications.",
    "csq.point3.title": "Results Interpretation",
    "csq.point3.description": "We analyze your data and provide actionable insights to maximize the ROI of your technology investment.",
    "csq.footer": "Committed to your operational success from day one",

    // ROI Section
    "roi.heading": "Culture is what happens when the boss isn't around",
    "roi.subtitle": "SIDÓN doesn't just digitize, it generates measurable impact on your costs and team effectiveness.",
    "roi.energy.title": "Energy Savings",
    "roi.energy.description": "Direct reduction in A/C and lighting consumption through intelligent monitoring.",
    "roi.productivity.title": "Increased Productivity",
    "roi.productivity.description": "Optimization of supervision time and effective execution of daily processes.",
    "roi.csq.badge": "Human support that guarantees your success",
    "roi.activity.title": "Real-Time Activity",
    "roi.activity.1": "Audit completed by Supervisor at North Branch",
    "roi.activity.2": "Preventive maintenance validated via Mantiz",
    "roi.activity.3": "Temperature report approved - Central Plant",
    "roi.activity.4": "Safety checklist completed - South Warehouse",
    "roi.activity.5": "Equipment inspection completed - Industrial Zone",
    "roi.activity.time.1": "5 min ago",
    "roi.activity.time.2": "12 min ago",
    "roi.activity.time.3": "18 min ago",
    "roi.activity.time.4": "25 min ago",
    "roi.activity.time.5": "32 min ago",
    "roi.cta.title": "Sustainable Qualitative Impact",
    "roi.cta.description": "Lower staff turnover and faster decisions based on real data.",
    "roi.cta.button": "Calculate My Return",

    // CSQ Commitment Section
    "csqSection.title": "Human Commitment: CSQ",
    "csqSection.subtitle": "More than Software, a Partner in Your Operation",
    "csqSection.card1.title": "Strategic Consulting",
    "csqSection.card1.description": "We customize SIDÓN according to your operation's specific needs. We don't sell a generic product, we co-create the solution with you.",
    "csqSection.card2.title": "Human Support",
    "csqSection.card2.description": "We speak your operational team's language. Our consultants are in the field, not just behind a desk, ensuring real adoption.",
    "csqSection.card3.title": "Results Evolution",
    "csqSection.card3.description": "We interpret your data and convert it into concrete actions. We measure ROI with you and adjust the strategy in real-time.",
    "csqSection.closing": "Our presence is critical to maintain the reliability of your operation 365 days a year.",
    "csqSection.closing.highlight": "reliability of your operation",

    // Mantiz Timeline
    "mantiz.badge": "Maintenance Management",
    "mantiz.title": "Complete Service Cycle",
    "mantiz.subtitle": "We automate and control the entire technical incident response cycle",
    "mantiz.node1.title": "Incident Report",
    "mantiz.node1.description": "Employee detects and reports a technical failure from their smartphone in real-time.",
    "mantiz.node1.imageAlt": "Employee reporting failure from smartphone",
    "mantiz.node2.title": "Smart Assignment",
    "mantiz.node2.description": "The system automatically assigns the task to the available technician based on location and specialty.",
    "mantiz.node2.imageAlt": "Admin dashboard assigning task",
    "mantiz.node3.title": "Field Validation",
    "mantiz.node3.description": "Technician scans QR code to validate location and register work start.",
    "mantiz.node3.imageAlt": "Technician scanning QR code",
    "mantiz.node4.title": "Evidence-Based Closure",
    "mantiz.node4.description": "Repair is validated with before and after photographic evidence, closing the ticket.",
    "mantiz.node4.imageAlt": "Ticket closure screen with evidence",
    "mantiz.cta": "Learn About Mantiz",

    // CTA
    "cta.title": "Start your digital transformation today",
    "cta.description": "Schedule a personalized demo and discover how SIDÓN can optimize your business operations with artificial intelligence and real-time data.",
    "cta.demo": "Request Free Demo",
    "cta.call": "Call Now",

    // Footer
    "footer.tagline": "Business Intelligence for retail. We transform data into intelligent decisions.",
    "footer.solutions": "Solutions",
    "footer.company": "Company",
    "footer.support": "Support",
    "footer.aboutUs": "About Us",
    "footer.successCases": "Success Cases",
    "footer.blog": "Blog",
    "footer.careers": "Careers",
    "footer.helpCenter": "Help Center",
    "footer.documentation": "Documentation",
    "footer.api": "API",
    "footer.systemStatus": "System Status",
    "footer.ecosat.title": "A company of",
    "footer.ecosat.tagline": "Technology solutions for the retail industry since 2008.",
    "footer.copyright": "© 2026 SIDÓN by ECOSAT. All rights reserved.",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.cookies": "Cookies",

    // Sense IoT Page
    "sense.hero.badge": "Internet of Things (IoT)",
    "sense.hero.title1": "Intelligence that feels,",
    "sense.hero.title2": "Data that acts.",
    "sense.hero.description": "Sidón Sense connects your physical infrastructure with your digital strategy. High-precision industrial sensors that transform every corner of your operation into a source of savings and control.",
    "sense.hero.cta": "Start monitoring",

    "sense.bento.cold.title": "Critical Cold Control",
    "sense.bento.cold.desc": "24/7 monitoring of chambers and refrigerators. Avoid waste due to broken cold chains.",
    "sense.bento.energy.title": "Energy Management",
    "sense.bento.energy.desc": "Visualize consumption in real-time. Detect inefficient equipment and electrical leaks.",
    "sense.bento.ambient.title": "Environmental Variables",
    "sense.bento.ambient.desc": "Humidity, CO2, and VOCs. Guarantee optimal environments for customers and products.",
    "sense.bento.assets.title": "Asset Health",
    "sense.bento.assets.desc": "Motor vibration and current. Predict failures before they stop your operation.",

    "sense.workflow.title": "From Sensor to Decision",
    "sense.workflow.step1.title": "Precise Capture",
    "sense.workflow.step1.desc": "Plug & Play industrial sensors measure critical variables every second.",
    "sense.workflow.step2.title": "Secure Transmission",
    "sense.workflow.step2.desc": "Gateways with military encryption send data via 4G or LoRaWAN.",
    "sense.workflow.step3.title": "Sidón Cloud",
    "sense.workflow.step3.desc": "AI algorithms analyze trends and detect anomalies instantaneously.",
    "sense.workflow.step4.title": "Closed Loop",
    "sense.workflow.step4.desc": "If something fails, DUMA assigns the task to the technician and closes the cycle.",

    "sense.benefits.title": "Direct Impact on your Bottom-Line",
    "sense.benefits.1.title": "Waste Reduction",
    "sense.benefits.1.desc": "Up to 30% less product loss due to refrigeration failures.",
    "sense.benefits.2.title": "Energy Savings",
    "sense.benefits.2.desc": "Schedule optimization and ghost consumption detection (-15% bill).",
    "sense.benefits.3.title": "Regulatory Compliance",
    "sense.benefits.3.desc": "Automatic reports for regulatory entities.",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("es")

  const t = useCallback(
    (key: string): string => {
      return translations[language][key] || key
    },
    [language]
  )

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
